### ISSUE TITLE
Reporting new version when update isn't available

### ISSUE THREAD

**Issue by andymac4182** [cleanflight/cleanflight-configurator#10]
11:40:34 -- You're using an old version of Cleanflight - Configurator. Please update so you can benefit from recently added features and bugfixes.

I am running Cleanflight - Configurator 0.51.1

**Comment by SleepyBrett** [comment]
So just going to raise this again. Wen't into hibernation over the winter, Getting everything set up for some summer flying and cleanflight configurator says it's an old version. Check the version it says 1.2.1, that seems to be the latest release here, and on the chrome store.

??
