### ISSUE TITLE
UI - Rework Mode configuration.

### ISSUE THREAD

**Issue by fiveangle** [cleanflight/cleanflight-configurator#100]
With greater # of channels supported, and the new multi-mode channel adjustment capability, CFC has outgrown the "display every possible channel" model of the AUX config page it inherited from BFC.

Suggested enhancement is for AUX config page show list of configured AUX channels, followed by a "Add..." form entry where entries are parametrized to all the available options.

The concept is similar in behavior to the following type of configuration for adding Port-forwarding entries on a router configuration web GUI, where a single entry-field below all currently-configured entries allows the user to add a new entry:

![portforwarding_basic_lg](https://cloud.githubusercontent.com/assets/2219447/6173414/d39d36e6-b29c-11e4-9203-884ca7f19c12.jpg)

This will greatly simplify (and clarify) the AUX channel configuration.  Additionally, it will allow for the possibility of the AUX config page to allow assigning multiple channels to a single feature (related to #101), which is not possible in CF/CFC today.

-=dave

**Comment by Ozzy33** [comment]
With 12/16 channel Rx, would be nice to have more than 4 channels (slots) for adjustment (also more adjustments added like the rest of PID's, (blackbox dataflash recording on/off or move to modes tab).
Thanks CF!!
