### ISSUE TITLE
Enhancement to allow multiple AUX channels to toggle/enable a single feature

### ISSUE THREAD

**Issue by fiveangle** [cleanflight/cleanflight-configurator#101]
Current CFC AUX configuration limits each feature to be assignable to only a single channel.

Suggestion is to allow multiple channels to be assigned to a feature, with the corresponding range adjustment (related to #100).

As an example, this would allow the BUZZER feature to be assigned to one channel for manually triggering the buzzer (to find a downed model, for instance), while also allowing BUZZER to be assigned to ANGLE + BARO mode of another channel that would be used by an acro pilot for "bailout" option.

This extends the Feature-to-Channel mapping from the current 1-to-1, to 1-to-many.

CF/CFC does not allow this configuration today (that I am aware of).

-=dave

**Comment by hydra** [comment]
You can add multiple ranges to a mode already via the add range button.

If i'm not understanding you please provide an example of what you want to do and re-open this.
