### ISSUE TITLE
unable to connect to board using OSX 10.6.8

### ISSUE THREAD

**Issue by piersh** [cleanflight/cleanflight-configurator#109]
I am able to connect to the board (flip32) with both a windows PC and a newer mac.

I am able to flash the firmware using [stm32flash](https://code.google.com/p/stm32flash/) running on 10.6.8, so presumably the CP210x drivers & usb hardware are ok.

I believe it may be related to this Chromium issue:
    https://code.google.com/p/chromium/issues/detail?id=448698

here are other users having the same issue:
    http://www.rcgroups.com/forums/showthread.php?t=1653753&page=86
    http://www.multiwii.com/forum/viewtopic.php?f=8&t=3414&start=50#p47397
    http://fpvlab.com/forums/showthread.php?13873-Naze32-Acro-Multiboot-controller-CC3D-compatible-FC-for-25&p=371571&viewfull=1#post371571

**Comment by hydra** [comment]
There are no maintainers that use this old version of OSX.  Won't fix unless someone submits a pull request. Sorry.
