### ISSUE TITLE
UI - Better support for high dpi displays

### ISSUE THREAD

**Issue by tannewt** [cleanflight/cleanflight-configurator#110]
All the text is tiny on my X1 Carbon 2014 display. Looks like all the css is in px but should probably be in em or some other display independent unit.

**Comment by tracernz** [comment]
Hmm, it works okay in high-dpi on OS X so this must be a Windows specific problem.

**Comment by tannewt** [comment]
I'm on Linux chrome which could be the problem now that I think about it. I
tried ctrl+ but that didn't increase my font size.

**Comment by hydra** [comment]
@tannewt A screenshot would really help here.

**Comment by tannewt** [comment]
Chrome 43 fixed Linux high dpi so it looks good now.
