### ISSUE TITLE
Mismatched endianness

### ISSUE THREAD

**Issue by rbirkby** [cleanflight/cleanflight-configurator#114]
MSP values are sent back in little-endian format. For MSP_BOARD_INFO, cleanflight sends back the hardware revision as:

```c
serialize16(hardwareRevision);
```

However, the configurator [reads](https://github.com/cleanflight/cleanflight-configurator/blob/development/js/msp.js#L551) this with:

```javascript
CONFIG.boardVersion = data.getUint16(offset);
```

which is a big-endian read.

**Comment by hydra** [comment]
done
