### ISSUE TITLE
Switching to 'Motors' tab when armed and motors running causes motors to continue running after disarm

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight-configurator#118]
Steps to reproduce:
1) connect a copter to configurator via serial or USB
2) stay at Setup tab or switch to Receiver tab (any other tab probably will trigger this as well)
3) arm a copter, ensure that motors are running
4) with motors still running switch to 'Motors' tab
5) disarm a copter
6) see motors still running and 'Motor test mode' checkbox activated.

**Comment by RandGH** [comment]
Yep, can confirm. Same here: https://github.com/cleanflight/cleanflight/issues/541
