### ISSUE TITLE
Motors - Rename the "Check" checkbox to something more sensible.

### ISSUE THREAD

**Issue by matvey83** [cleanflight/cleanflight-configurator#119]
I think UX will be better if the "Check" checkbox was renamed to something that describes the confirmed action, for example: "Props are off"

**Comment by wolfpackt99** [comment]
The checkbox label should be "Enable Motor Test Mode". Which is what the checkbox is doing. Clearly states above that to take props off.

**Comment by hydra** [comment]
"I understand the risks"

**Comment by hydra** [comment]
Done

**Comment by wolfpackt99** [comment]
awesome.
