### ISSUE TITLE
ARM switch not showing GREEN when Armed

### ISSUE THREAD

**Issue by max3228** [cleanflight/cleanflight-configurator#12]
Hello Dominic,
Firstly many thanks for all the development time you and the other contributors have given to Cleanflight codebase and Configurator.

I have a minor issue where I cannot get the Arm to turn green on the Aux Config Tab. It used to work in an older version of Configurator (I think it was 50.1)

Here are my stats:
Cleanflight Configurator: 0.51.4
Naze32 Rev. 5 FC
Firmware # version: Cleanflight / NAZE Nov 8 2014 19 (28da97f)/ 12:32:
Running - OS: Windows XP Home 32 bit, Chrome: 38.0.2125.111
Blackout Mini H Quad – Tiger MN2206 motors – Tiger 12 Amp ESC’s – Turnigy 3 Amp UBEC – Minim OSD – UBLOX Neo 6M GPS - Fatshark 5.8 GHz 250mW VTx - Mini DC-DC Converter 3 Amp – 16 x 2812B Addressable LED Strip – Crius Bluetooth Module – FrSKY D8-XP Receiver – Taranis X9D Transmitter.
Regards,
Mike (max3228)

![screen grab1](https://cloud.githubusercontent.com/assets/8843694/5058781/ed283412-6cf6-11e4-94e1-d6a3b7eaa986.jpg)

Screen grab above showing ARM not turning GREEN when armed on my Taranis X9D Tx.
# dump
# version

Cleanflight/NAZE Nov 8 2014 / 12:32:19 (28da97f)
# dump master
# mixer

mixer QUADX
# feature

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature RX_PPM
feature VBAT
feature MOTOR_STOP
feature GPS
feature FAILSAFE
feature TELEMETRY
feature LED_STRIP
# map

map AETR1234
# led

led 0 15,15:SD:IA
led 1 8,8:E:WF
led 2 8,7:E:WF
led 3 15,0:ND:IA
led 4 7,7:N:WF
led 5 8,7:N:WF
led 6 0,0:ND:IA
led 7 7,7:W:WF
led 8 7,8:W:WF
led 9 0,15:SD:IA
led 10 7,8:S:WF
led 11 8,8:S:WF
led 12 7,7:D:WF
led 13 8,7:D:WF
led 14 7,7:U:WF
led 15 8,7:U:WF
led 16 0,0::
led 17 0,0::
led 18 0,0::
led 19 0,0::
led 20 0,0::
led 21 0,0::
led 22 0,0::
led 23 0,0::
led 24 0,0::
led 25 0,0::
led 26 0,0::
led 27 0,0::
led 28 0,0::
led 29 0,0::
led 30 0,0::
led 31 0,0::
# color

color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 150,0,255
color 15 150,0,255

set looptime = 3500
set emf_avoidance = 0
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set input_filtering_mode = 0
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set retarded_arm = 0
set disarm_kill_switch = 1
set small_angle = 25
set flaps_speed = 0
set fixedwing_althold_dir = 1
set serial_port_1_scenario = 1
set serial_port_2_scenario = 2
set serial_port_3_scenario = 0
set serial_port_4_scenario = 0
set reboot_character = 82
set msp_baudrate = 115200
set cli_baudrate = 115200
set gps_baudrate = 115200
set gps_passthrough_baudrate = 115200
set gps_provider = 1
set gps_sbas_mode = 0
set gps_auto_config = 0
set serialrx_provider = 0
set telemetry_provider = 0
set telemetry_switch = 0
set frsky_inversion = 0
set frsky_default_lattitude = 0.000
set frsky_default_longitude = 0.000
set frsky_coordinates_format = 0
set frsky_unit = 0
set frsky_battery_size = 0
set vbat_scale = 111
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 34
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = 0
set align_gyro = 0
set align_acc = 0
set align_mag = 0
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set max_angle_inclination = 500
set gyro_lpf = 42
set moron_threshold = 32
set gyro_cmpf_factor = 600
set gyro_cmpfm_factor = 250
set yaw_control_direction = 1
set acc_hardware = 0
# dump profile
# profile

profile 0
# aux

aux 0 0 0 1600 2100
aux 1 2 1 1400 2100
aux 2 3 1 1400 2100
aux 3 4 1 1400 2100
aux 4 5 3 1800 2100
aux 5 9 1 1800 2100
aux 6 10 1 1400 1600
aux 7 20 2 1800 2100
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900
aux 20 0 0 900 900
aux 21 0 0 900 900
aux 22 0 0 900 900
aux 23 0 0 900 900
aux 24 0 0 900 900
aux 25 0 0 900 900
aux 26 0 0 900 900
aux 27 0 0 900 900
aux 28 0 0 900 900
aux 29 0 0 900 900
aux 30 0 0 900 900
aux 31 0 0 900 900
aux 32 0 0 900 900
aux 33 0 0 900 900
aux 34 0 0 900 900
aux 35 0 0 900 900
aux 36 0 0 900 900
aux 37 0 0 900 900
aux 38 0 0 900 900
aux 39 0 0 900 900
# adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

set gps_pos_p = 11
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 20
set gps_posr_i = 8
set gps_posr_d = 45
set gps_nav_p = 14
set gps_nav_i = 20
set gps_nav_d = 80
set gps_wp_radius = 200
set nav_controls_heading = 1
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set alt_hold_deadband = 40
set alt_hold_fast_change = 1
set deadband = 0
set yaw_deadband = 0
set throttle_correction_value = 0
set throttle_correction_angle = 800
set yaw_direction = 1
set tri_unarmed_servo = 1
set default_rate_profile = 0
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1200
set failsafe_min_usec = 985
set failsafe_max_usec = 2115
set gimbal_flags = 1
set acc_lpf_factor = 4
set accxy_deadband = 40
set accz_deadband = 40
set accz_lpf_cutoff = 5.000
set acc_unarmedcal = 1
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf = 0.600
set baro_cf_vel = 0.985
set baro_cf_alt = 0.965
set mag_declination = -220
set pid_controller = 0
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_pitchf = 2.500
set i_pitchf = 0.600
set d_pitchf = 0.060
set p_rollf = 2.500
set i_rollf = 0.600
set d_rollf = 0.060
set p_yawf = 8.000
set i_yawf = 0.500
set d_yawf = 0.050
set level_horizon = 3.000
set level_angle = 5.000
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 90
set i_level = 10
set d_level = 100
set p_vel = 120
set i_vel = 45
set d_vel = 1
# dump rates
# rateprofile

rateprofile 0

set rc_rate = 90
set rc_expo = 65
set thr_mid = 50
set thr_expo = 0
set roll_pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
# 
# feature

Enabled features: RX_PPM VBAT MOTOR_STOP GPS FAILSAFE TELEMETRY LED_STRIP

**Comment by Proofbenny** [comment]
Hi I am having the same issue

**Comment by kvanvranken** [comment]
Same issue as well with a brand new flash just setting it up and cannot get the ARM to activate

**Comment by tomav** [comment]
Same problem, can have angle/horizon/baro to green, but not ARM.

**Comment by Zappes** [comment]
Same problem here.

**Comment by tomav** [comment]
I found that it was my TX endpoints that were not configured correctly.
They must be *inside* the baseflight throttle range:
The min must be >= to the min baseflight, the max must be <= to the max in baseflight.

**Comment by Zappes** [comment]
I solved the problem tonight, and the general idea is the same as in tomav's case. In my case I didn't adjust the ranges in Cleanflight, though. I just set the scaling of the throttle value in my Spektrum DX6i to 125% - after that, everything worked perfectly.

**Comment by max3228** [comment]
@hydra, @tomav, @Zappes, @Proofbenny @thenickdude 
Sorry Dominic and everyone else ..... Dominic was right it was a configuration error with my Taranis Tx @tomav you were spot on and thankyou all for your comments.
max3228

**Comment by thenickdude** [comment]
"The min must be >= to the min_throttle baseflight, the max must be <= to the max_throttle in cleanflight."

@tomav: this is not true, min_throttle and max_throttle define the signals sent to the ESCs, they have no relationship at all to the throttle value that your receiver sends.

**Comment by SleepyBrett** [comment]
I'm having this same issue. In the receiver tab all the channels run in the 1000-2000 range properly. But when I flip my aux1 channel switch to the proper position for arming the header in the modes tab stays frustratingly red.

So I have one question and one possible feature suggestion:
1) How do I go about troubleshooting this. The UI doesn't surface any kind of failure state.

And my feature request is:
1) When you set the mode to arm the UI should surface whatever is preventing the arm.

**Comment by thenickdude** [comment]
Show a screenshot of the receiver tab when you're trying to arm, and a screenshot of the modes tab (you can drag and drop screenshots into the window at GitHub and they'll be inserted into your reply)

**Comment by bbbenji** [comment]
I am having this problem but it is intermittent... I have played with the min/max on Taranis as suggested but does not help. Screenshots here: http://imgur.com/a/URLWR

**Comment by thenickdude** [comment]
It looks like it's refusing to arm due to too much tilt on the board or throttle not idle (I note that all the non-arming switches seem to work fine). If the board is level and throttle is at 1000, try recalibrating the accelerometer.

**Comment by bbbenji** [comment]
Should have mentioned I have tried all of that numerous times. And can verify that this only happens on the versions of BF/CF specified. Furthermore it does arm intermittently as seen in the video and no other variables have changed during those moments.

**Comment by acidhax** [comment]
I had this issue--- and all I had to do was Calibrate the Accelerometer...

**Comment by kurttan** [comment]
@Zappes You really save my day! Same issue and have been struggling for 2 days but you point me to the right solution/workaround. Thanks!

**Comment by BearcatF8** [comment]
@Zappes thank a lot. I've been dealing with a DX9 and Banggood QX70 and Cleanflight for one day and you solved my problem.

**Comment by bkhti4** [comment]
Hi I'm having same problem. Quadcopter randomly gets armed sometimes although settings are same. Any suggestions?

**Comment by Ksuday0407** [comment]
I am facing same problem too, but I use FS-CT6B Tx. We get response from tx to cleanflight but not get it to the servos

**Comment by Ksuday0407** [comment]
Any one have solution please respond
