### ISSUE TITLE
Adjustment setup gets deleted if not enabled.

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/cleanflight-configurator#121]
I setup 8 items in the adjustment page, click save, all good at this point.

I use thro trim for on-off-on adjustments, but I only want a couple adjustments used at a time, so I uncheck the "If enabled" box, save, poof, all are gone except the only enabled adjustments. 

CF v1.7.2 (feb 23), CFC 0.62.0, Flip32+

I am really enjoying all the new features, thanks for all the hard work!!!

**Comment by hydra** [comment]
The way this works is due to the implementation of the firmware.  Though yes, I agree it's not helpful.  Perhaps request a firmware change and reference this issue it it's an issue.
