### ISSUE TITLE
pid profiles should be having a modeswitch abiltiy 1-3

### ISSUE THREAD

**Issue by Petfrogg** [cleanflight/cleanflight-configurator#125]
Since we are all tweakers it would be nice to able to set a swith to be related to different pid-profiles. Would be nice to change and test midflight.

**Comment by cjbraden** [comment]
I second. I thought I could do this already, but on further investigation,
I figured out it was not possible.

I can understand why mid-flight would be a bad idea, but connected with the
craft disarmed would be fine too. So, land, disarm, switch profile, arm,
take off... would very much love to have this.

**Comment by hydra** [comment]
This is a firmware issue, there is already a request for this firmware feature.  Please search.
