### ISSUE TITLE
Cleanflight quad image fix

### ISSUE THREAD

**Issue by 3flyguy3** [cleanflight/cleanflight-configurator#129]
The quad image in Cleanflight config has changed to an image of a 'brick'. See attached. Why? How do I fix?
(Is this the correct support page for Cleanflight? I was directed to this page by a more experienced user.)
![img_4053](https://cloud.githubusercontent.com/assets/11441229/6620578/99a7fb60-c89f-11e4-91c3-0a26608e331e.JPG)

**Comment by thenickdude** [comment]
That looks like your Web browser has fallen back to software rendering for
3D graphics. Normally when a decent graphics card is available it is able
to use WebGL (OpenGL) which allows the full 3D models to be displayed.

You could try installing the latest driver for your video card.
