### ISSUE TITLE
motors stop when i switch from manual mode to angle or horizon mode 

### ISSUE THREAD

**Issue by Tarekddo** [cleanflight/cleanflight-configurator#131]
I’m setting my naze 32 using cleanflight and frsky tiranis tx when i switch from manual mode to angle or horizon mode the motors stop if i go back to manual the motors will not stars until i arm agin any clue please

**Comment by hydra** [comment]
This is the issue tracker for the GUI, sounds like you have a firmware issue or need help with configuration, this is the place for neither.  Please use forums and IRC for support.  Please use the firmware issue tracker for firmware issues.
