### ISSUE TITLE
Profile number is 1, 2 and 3 on pid the tab and 0,1 and 2 on cli command

### ISSUE THREAD

**Issue by rocky77** [cleanflight/cleanflight-configurator#135]
It could be interesting to give the same number profile on the cli command and the pid tab. It's a suggestion.

**Comment by rocky77** [comment]
Is someone understand what I wrote ? :)

**Comment by hydra** [comment]
CLI != GUI.  GUI representation doesn't have to follow CLI representation or even firmware internals.
