### ISSUE TITLE
PID Tuning - Enable only the controls that are appropriate based on available sensors.

### ISSUE THREAD

**Issue by pfriedel** [cleanflight/cleanflight-configurator#137]
It might be helpful for new people to disable the PID settings for hardware that doesn't use them anyway - i.e. on a Gyro/Accel board, having PID settings available for Pos/PosR/NavR only adds to a wall of numbers that won't have any affect on flight performance.

Broadly speaking, I'm thinking that a Naze32 Acro should only show ROLL, PITCH, YAW, and LEVEL, I'd think?  ALT requiring a baro, VEL, Pos, PosR, NavR requiring GPS.

And similarly, if there are any PID controllers that don't use a term (PI only, PD only, etc), disabling the term that isn't doing anything anyway would help people understand that tuning that dial won't affect anything.

**Comment by ummagawd** [comment]
good idea. I'd also add to remove any other variables that are unaffected..... such as TPA for certain PID controllers.

**Comment by hydra** [comment]
Agreed, this will certainly help new users.

**Comment by wwkayak** [comment]
I actually never really noticed them them until @DigitalEntity started his fork, now I'm back looking at exactly what they are... so ya, not needed.

**Comment by skaman82** [comment]
This is done already in 1.0
