### ISSUE TITLE
Select UART on version 1.8

### ISSUE THREAD

**Issue by Vincent81** [cleanflight/cleanflight-configurator#138]
Hello,
On 1.8 selecting UART is bad and does not work.
flash the 1.7 puts everything well.
![cleanflight-1-8](https://cloud.githubusercontent.com/assets/962113/6710688/970618fa-cd82-11e4-8d53-0e91a1c6ab67.png)

**Comment by rocky77** [comment]
Please, read the releases notes.  You need CF-configurator v0.63!

--- Message initial ---

De : "Vincent" <notifications@github.com>
Envoyé : 18 mars 2015 15:23
A : "cleanflight/cleanflight-configurator" <cleanflight-configurator@noreply.github.com>
Objet : [cleanflight-configurator] Select UART on version 1.8 (#138)

Hello,
On 1.8 selecting UART is bad and does not work.
flash the 1.7 puts everything well.
![cleanflight-1-8](https://cloud.githubusercontent.com/assets/962113/6710688/970618fa-cd82-11e4-8d53-0e91a1c6ab67.png)


---
Reply to this email directly or view it on GitHub:
https://github.com/cleanflight/cleanflight-configurator/issues/138

**Comment by Vincent81** [comment]
thank you for your answer.
I had searched an update, but I found nothing.
I even tried the zip locally ..
Can you tell me where to find this version?

**Comment by rocky77** [comment]
Here : https://github.com/cleanflight/cleanflight-configurator/tree/baseflight-configurator-development


--- Message initial ---

De : "Vincent" <notifications@github.com>
Envoyé : 18 mars 2015 15:50
A : "cleanflight/cleanflight-configurator" <cleanflight-configurator@noreply.github.com>
Cc: "rocky77" <r_roque77@hotmail.com>
Objet : Re: [cleanflight-configurator] Select UART on version 1.8 (#138)

thank you for your answer.
I had searched an update, but I found nothing.
I even tried the zip locally ..
Can you tell me where to find this version?

---

**Comment by Vincent81** [comment]
Ok I just found.
Yesterday I had to download the correct zip.
thank you.
