### ISSUE TITLE
Allow configuration of ublox GPS message rates.

### ISSUE THREAD

**Issue by l2smith2** [cleanflight/cleanflight-configurator#14]
I have several neo6m gps modules that work really well with normal multiwii at 5hz 115200baud.
Cleanflight will sometimes change the module refresh rate to 10hz which is giving it greatly reduced position hold performance.

Is there anyway to stop cleanflight from configuring the GPS module automatically. It should be written in the GPS docs if so.

**Comment by Hands0n** [comment]
Absolutely agree - first get the basic GPS functions stable and working well.  I have built an "experimenter" ZMR250 with PA6C GPS (see: http://www.ebay.co.uk/itm/280890908793?_trksid=p2059210.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT ) - also have use of uBlox NEO-6M GPS (CN06-v2).  Currently GPS_Hold and GPS_Home exhibiting "quaint" behaviours. :-)

**Comment by hydra** [comment]
Closing this, requires firmware changes, we can re-open if the firmware gets updated.
