### ISSUE TITLE
Save button not working in some Tabs

### ISSUE THREAD

**Issue by Klakinoumi** [cleanflight/cleanflight-configurator#141]
Just flashed my naze32 with 1.8.0. Cleanflight configurator is 0.62.1
In some tabs (see below) the save button is not working anymore.

Port tab : not working
Configuration : not working
PID Tuning : not working
Receiver : not working
Modes : Working OK
Adjustement : not working
LED Strip : not working
Saving in CLI : Working OK

It is worth noting that when pressing the save button in a non-working tab, the number of packet error is rising.

**Comment by hydra** [comment]
This us about the 5th issue were someone has not read the release notes!  I don't like to shout, but my patience is wearing thin today, sorry: READ THE RELEASE NOTES and use the correct configurator.
