### ISSUE TITLE
Failsafe settings not present in backup

### ISSUE THREAD

**Issue by skyflyer** [cleanflight/cleanflight-configurator#143]
When I backup the settings using Cleanflight Chrome app, only one failsafe setting is written to backup json file -- `failsafe_throttle`. Other values are missing. They are visible in the CLI dump, however.

**Comment by hydra** [comment]
Currently he configurator can only back up settings which are exposed via MSP.  The other settings you mention are not suppoted.

**Comment by tricopterY** [comment]
@hydra - I am working on this enhancement with introducing new MSP codes:
```C
#define MSP_FAILSAFE_CONFIG             75 //out message         Returns FC Fail Safe settings
#define MSP_SET_FAILSAFE_CONFIG         76 //in message          Sets FC Fail Safe settings
```
Just waiting for the 1.9.0 fix related to cleanflight/cleanflight/#774

**Comment by hydra** [comment]
don't work on this until the new failsafe code is merged in to 1.9.0 please otherwise it will need re-work.

**Comment by tricopterY** [comment]
Thanks for the heads-up, I will wait.

**Comment by hydra** [comment]
Should be fixed, please re-open if not.
