### ISSUE TITLE
Latest Cleanflight not compatible with configurator in Chrome web store

### ISSUE THREAD

**Issue by xoxota99** [cleanflight/cleanflight-configurator#146]
Latest Cleanflight (for naze, Cleanflight/NAZE 1.8.0 Mar 20 2015 / 18:39:17 (730d0fe)) supposedly requires configurator 0.63 or higher, which is not actually available in the Chrome web store. Where can I get it?

**Comment by thenickdude** [comment]
The link is in the release notes for Cleanflight 1.8.0:

https://github.com/cleanflight/cleanflight/releases/tag/v1.8.0

Follow the instructions in the readme on the page it links to install that.
