### ISSUE TITLE
Mixer - Custom mixer editor

### ISSUE THREAD

**Issue by toasthall** [cleanflight/cleanflight-configurator#149]
I have been thinking about an editor for custom mixers. What I envisage is a graphical interface with a graph that adds the motor location by entering the pitch and roll distances from the centre of the frame (or FC location). Calculation would be 1 divided by the value of the largest axis (ignoring the sign) then multiplying that figure by the distance for the particular motor.

I think this would simplify mixes for custom frames or frames like spiderquads, v-tails or a-tails (can't figure out yet how to calculate values to take account of motor angles)

**Comment by hydra** [comment]
yes it would be very useful.  Fancy having a go at it?

**Comment by toasthall** [comment]
Yes I do, the problem is the last time I did anything HTML was in the 90's. Might still give it a go though.

**Comment by toasthall** [comment]
Hi Dominic,
Not sure how this all works. Is there any info or templates that might be useful for me in regards to attempting this?

cheers,

Dale

**Comment by tricopterY** [comment]
I would be interested in this too. The calculation should first attempt, finding the Centre of Thrust, using the typed in values relative to the Roll/Pitch axis. Then create values for motorMixer table, taking into account Yaw rotation signs. 
Also, template should suggest best mounting position for FC i.e CoT closest to CoM.
@toasthall - you can use Configurator Tabs, as a template, led_strip.html and led_strip.js, should give you a heads-up.

**Comment by toasthall** [comment]
Thanks @tricopterY 
I am still trying to wrap my head around the maths behind it all. I think to begin with, to make it simple for me, I will base the measurements off of the center of the FC board which i think should give a reasonable indication of the board's location in regards to the motors, that way people can play with board placement as well.

**Comment by tricopterY** [comment]
Just a bit of hint - it's best to calculate the Center of Thrust against two imaginary axes eg Y-roll axis and X-pitch axis, at an offset relative to the center of the FC board. The maths would take care of the calculated measurements, as you would be measuring a certain distance from Y and X datums.
Y
|     M1       M2
|            +
|___________  X

The plus sign represents the calculated CoT relative to Y and X. 
Asterisk represents multiplication.
CTx = (T1 * M1X1 + T2 * M2X2) / T1+T2
In your calculation you would use Unity (one) for values T1 and T2. 
M1X1 and M2X2 are distances of motors M1 and M2 along X axis from Y axis, hence CTx. 
You would repeat the same for X axis i.e CTy = (T1 * M1Y1 + T2 * M2Y2) / T1+T2

**Comment by toasthall** [comment]
Hi Guys,

Turns out I have no idea what I am doing with regards to developing this, if anyone else is interested in giving it a go that would be great.

Dale

**Comment by skaman82** [comment]
will look into this in the next weeks

**Comment by Rob2160** [comment]
Here you go.  Does V-Tails also. 

https://dl.dropboxusercontent.com/u/62849459/NAZE%20MIX%20Calculator%20V5.xlsx

**Comment by skaman82** [comment]
Working on this with @NightHawk32. The progress is posted here: https://github.com/skaman82/cleanflight-configurator/issues/54
Starting with a Quad X Mixer interface.

**Comment by skaman82** [comment]
@NightHawk32 any news on this?
