### ISSUE TITLE
CLI issue with AUX command higher than AUX 9

### ISSUE THREAD

**Issue by michelp29** [cleanflight/cleanflight-configurator#154]
Abstract :
When trying to restore a dump in cli from a previous dump made with fw 1.6.0,
it leads me to "modes" configurations not restored at all,
so i manage to read the whole log from cli, and appart
from syntaxe errors due to fw version changes, 
I pointed a weird problem with AUX command not correctly read by the CLI
only in some conditions.

Details :
Chrome: 41.0.2272.118, Configurator: 0.63.0
naze32 (afro accro), 
reproduced with firmware v1.8.0 (stable) and v1.8.1(RC),
all prefs reset to defaults before each tests ("defaults" in cli)

CLI : if I copy-past this :
```
# profile
profile 0

# aux
aux 0 0 0 1700 2100
aux 1 1 1 900 1300
aux 2 2 1 1300 1700
aux 3 12 2 1700 2100
aux 4 20 3 1700 2100
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
```
I get this on the screen :
(wrong interpretation of aux 0)
```
# # profile

# profile 0
profile 0

# # aux

# 900

# 1700 2100

# aux 1 1 1 900 1300

# aux 2 2 1 1300 1700

# aux 3 12 2 1700 2100

# aux 4 20 3 1700 2100

# aux 5 0 0 900 900

# aux 6 0 0 900 900

# aux 7 0 0 900 900

# aux 8 0 0 900 900

# aux 9 0 0 900 900

# aux 10 0 0 900 900

#
```
but if I copy past this :
(just removing last line "aux 10")
```
# profile
profile 0

# aux
aux 0 0 0 1700 2100
aux 1 1 1 900 1300
aux 2 2 1 1300 1700
aux 3 12 2 1700 2100
aux 4 20 3 1700 2100
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
```
all is ok with aux 0 ok too :
```
# # profile

# profile 0
profile 0

# # aux

# aux 0 0 0 1700 2100

# aux 1 1 1 900 1300

# aux 2 2 1 1300 1700

# aux 3 12 2 1700 2100

# aux 4 20 3 1700 2100

# aux 5 0 0 900 900

# aux 6 0 0 900 900

# aux 7 0 0 900 900

# aux 8 0 0 900 900

# aux 9 0 0 900 900
```
same thing if "defaults" is also made between this two tests
to reset all confs.
same thing if AUXs commands are in the middle of a complete dump.

so it appears that just having "aux 10" leads to trouble...

**Comment by hydra** [comment]
Can't replicate, firmware issue.  If you can provide steps to replicate in latest firmware please create a new issue in the firmware issue tracker (not the GUI issue tracker).
