### ISSUE TITLE
Feature request - Failsafe end of flight protection

### ISSUE THREAD

**Issue by HV40** [cleanflight/cleanflight-configurator#157]
hi,
This is feature request following me messing up in the field, I disarmed my quad after the flight and then switched off my transmitter before powering off the quad => this triggered the failsafe as designed, motors spinning... no harm done though.

I though a way to prevent this would be to disable the failsafe after a certain period of time after disarming the board, if the channel that is checked for failsafe is still valid.

Maybe it's a bit confusing to understand, let me try to put it simpler :
Disarming board => start timer => time elapsed (say 1sec) => other channels valid ? Yes => disable failsafe.

Failsafe being always armed when the board is armed.

The reason for the timer is to dissociate this scenario from the actual failure of the tx/rx where you could have the failsafe switched detected as disarmed when the link is actually failed.

I believe this would render the board more safe to idiots like me :)

**Comment by hydra** [comment]
You raised this in the configurator issue tracker instead of in the firmware issue tracker. Please recreate in the right tracker.
