### ISSUE TITLE
CurrentDraw is always displayed positive

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight-configurator#18]
`InitialSetup - Info - Current draw:` is always displayed as positive value, event when actual value is negative. This is very confusing when adjusting `current_meter_offset` in cli ..

**Comment by Roeland54** [comment]
I looked into this I think the problems is in the serial_msp.c

        if(masterConfig.batteryConfig.multiwiiCurrentMeterOutput) {
            serialize16((uint16_t)constrain((abs(amperage) * 10), 0, 0xFFFF)); // send amperage in 0.001 A steps
        } else
            serialize16((uint16_t)constrain(abs(amperage), 0, 0xFFFF)); // send amperage in 0.01 A steps
        break;

The use of the "abs" command and the use of a unsigned integer both make it impossible to have a negative value.

a.t.m. I am not setup to change and test cleanflight code so somebody else should solve this problem. 
(setting up eclipse is on the todo list)

In the configurator the following line should also change to match the corrected code in cleanflight:
msp.js:
                ANALOG.amperage = data.getUint16(5, 1) / 100; // A

**Comment by ledvinap** [comment]
Great work, thanks! I'll fix it ASAP

**Comment by hydra** [comment]
@ledvinap are you looking into this?  There have been some changes recently to the current meter code and it would be a good idea idea include this fix in the next release with the other current meter changes.

**Comment by ledvinap** [comment]
Sorry, got stuck on this one 

ABS in https://github.com/cleanflight/cleanflight/blob/master/src/main/io/serial_msp.c#L833 is the culprit. One possible solution is: 
https://github.com/ledvinap/cleanflight/blob/local/src/main/io/serial_msp.c#L834

Current will be limited from -320 to 320A (that may be enough unless you are flying a welding machine ... ) for msp and negative value displayed as zero with old multiwii display ...

Should I generate PR?

**Comment by hydra** [comment]
yeah, please do, thanks @ledvinap

**Comment by hydra** [comment]
@ledvinap and one for the configurator too, if needed

**Comment by hydra** [comment]
Fixed
