### ISSUE TITLE
Configuration - Enable Serial Receiver Provider section only when applicable

### ISSUE THREAD

**Issue by dngrlux** [cleanflight/cleanflight-configurator#187]
If the Serial Receiver Provider section isn't applicable to those on RX_PPM, the interface could be cleaned up by disabling that section.

The Setup and Adjustment tabs currently do this with some items, and it seems that this could be applied to the Configuration tab for Serial Receiver Provider and the numerical voltage levels below VBAT. I remember having to go into Rx.md to get clarity on the options that didn't pertain to my configuration when I first started using Cleanflight.

**Comment by hydra** [comment]
Agreed.
