### ISSUE TITLE
CLI ignoring multiple spaces

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight-configurator#192]
Multiple spaces are displayed as single one. Is this intentional?

**Comment by hydra** [comment]
Got an example? Step to reproduce?

**Comment by ledvinap** [comment]
Just enter 'a     b', it gets echoed back as 'a b'.

I tried indenting output, it does not work ...

**Comment by thenickdude** [comment]
This is a consequence of outputting to HTML, which treats consecutive whitespace characters as one character.

**Comment by ledvinap** [comment]
So all that is needed is `<pre>` or css equivalent?
