### ISSUE TITLE
Aeroplane config

### ISSUE THREAD

**Issue by airship100** [cleanflight/cleanflight-configurator#204]
Hi
is it possible to add a 2nd motor to aeroplane config to a allow diif thrust with yaw control.

thanks

**Comment by MauroMombelli** [comment]
this should be asked to cleanflight, as this require a heavy rewrite of the plane logic. Look at src/flight/mixer.c to see how a plane "think"

**Comment by AustinSaintAubin** [comment]
This is doable now with custom airplane config.
Solved in & Duplicate of #248

**Comment by skaman82** [comment]
this seems to be already done, if not please reopen
