### ISSUE TITLE
Rename Serial Receiver Provider from XBUS_MODE_B to MULTIPLEX_SRXL

### ISSUE THREAD

**Issue by McClean0815** [cleanflight/cleanflight-configurator#205]
The serial receiver provider XBUS_MODE_B should be renamed to MULTIPLEX_SRXL because Multiplex Modellsport is the founder of the srxl protocol. JR is just using it.

Or perhaps 2 selections can be used - XBUS_MODE_B and MULTIPLEX_SRXL

The technical protocol-specification can be downloaded on the multiplex web site:
http://www.multiplex-rc.de/service/downloads/schnittstellenbeschreibungen.html

**Comment by andyshinn** [comment]
Spektrum is now starting to tout the SRXL name under their [new AR7700 receiver](http://www.spektrumrc.com/Products/Default.aspx?ProdId=SPMAR7700) as well.
