### ISSUE TITLE
Allow global configuration for some profile items

### ISSUE THREAD

**Issue by nine-fpv** [cleanflight/cleanflight-configurator#209]
Would it be possible to create an option (a checkbox or something similar) to make certain configuration items apply globally across all three profiles?

for example, if the mode and adjustment tabs had a global check box it would save time for people who don't need these to be profile dependant.

**Comment by DeetAus** [comment]
VBAR (helicopter FBL unit) has a feature that lets you copy all parameters between profiles
You can select to copy the current to a specific profile or to all profiles

I found it really handy, you setup profile1 as a base setup, copy that to all profiles, then simply edit the required changes on the other profiles
