### ISSUE TITLE
custom mix animation on setup tab looks strange in new version

### ISSUE THREAD

**Issue by kaefert** [cleanflight/cleanflight-configurator#210]
Hi there!

I'm using a custom motor mix because my first motor pin died, so I fly my quadcopter using motor outputs 2 to 5 instead of 1 to 4. (see also https://github.com/cleanflight/cleanflight/issues/882 )

In previous configurator versions, I saw a simple rectlinear "box" with 6 labeled (front, left, ...) sides.
In the current version: `Running - OS: Linux, Chrome: 43.0.2357.81, Configurator: 0.65.0`
* the shape of this box seems to change on movement, and every of the previous 6 sides seems to be split into 2 along its diagonal into 2 same sized triangles.
* the labels are distorted.

![screenshot from 2015-06-12 1847_21](https://cloud.githubusercontent.com/assets/1448723/8135079/b5336fda-1134-11e5-8f9f-566bfcae38ee.png)

**Comment by DanNixon** [comment]
It looks like the texture coordinates are not being corrected for the perspective correctly (texture coordinates should be divided by the depth before interpolation).

**Comment by skaman82** [comment]
solved in https://github.com/cleanflight/cleanflight-configurator/commit/a133eb63749b0109e226b326c41f448be65997d3
