### ISSUE TITLE
Built in documentation/help

### ISSUE THREAD

**Issue by stylr82** [cleanflight/cleanflight-configurator#213]
Been giving some thought to adding built in help into the configurator. Basicly the concept is to have help icon next to each feature heading (e.g. Board Alignment)  When the user clicks the icon they are given a brief overview on what the each of parameters do, then perhaps have links off to the manual/documentation for more detailed info.

Have done a quick mockup of my idea - Just using jquery-ui to display a dialog. Just wanted to get some feedback to see if the idea is worth pursuing?

![context help mockup](https://cloud.githubusercontent.com/assets/12956871/8239722/922e2852-15f5-11e5-8ff7-16958ade02b6.PNG)

Also had a couple of thoughts around pulling in text from the .md docs and parsing text from them, but the docs would need to be consistently structured/titled for this to work effectively.

**Comment by borisbstyle** [comment]
Looks good!

**Comment by tracernz** [comment]
Excellent idea. :+1:

**Comment by JohnOCFII** [comment]
Great idea!  If you have the skills to add it, I'm sure others will chime in with some of the more esoteric content.

**Comment by thenickdude** [comment]
Yes this is very badly needed, especially for variables like `min_throttle` which everybody seems to think is related to their throttle lever on their Tx.

**Comment by stylr82** [comment]
Ok, so I think this is worth perusing, I'll start work on this

**Comment by stylr82** [comment]
I've done a pull request for this now, if anyone is interested in having a look. That's the easy bit though, writing up the various dialogs is going to take a bit of time

https://github.com/cleanflight/cleanflight-configurator/pull/217

**Comment by skaman82** [comment]
This feature is already implemented in v 1.0

**Comment by skaman82** [comment]
Closing
