### ISSUE TITLE
Luxfloat Needs more decimals for tuning

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/cleanflight-configurator#219]
The configurator should support full 3 decimals of luxfloat

It should be like this
![image](https://cloud.githubusercontent.com/assets/10757508/8768113/3d823bee-2e74-11e5-91c0-757c07fd3ee8.png)

**Comment by zenman8269** [comment]
So, does that mean you can use them in cli for the p term? In other words instead of 0.8 , 0.7, etc, use 0.85, 0.86, etc?

**Comment by borisbstyle** [comment]
P supports up to 3 decimals
You can also have 0.852 for P.
But I and D can also have more as well.
Op 19 jul. 2015 08:59 schreef "zenman8269" <notifications@github.com>:

**Comment by zenman8269** [comment]
ok...I didn't know that. I have not been able to tune out some oscillations with roll p at 0.8 and 0.7 feels too loose. Will have to give 0.750 a try. Thanks :)

**Comment by borisbstyle** [comment]
we are tuning in big steps now.

comparing p to PID1:
tuning step for p of 0.1 in luxfloat is same like 3.2 increase in pid1.
Op 19 jul. 2015 19:45 schreef "zenman8269" <notifications@github.com>:

**Comment by zenman8269** [comment]
So what about D term? It looks like in lux 18 is 0.018,  can you add decimals to it?
D term is not so bad, and I therm steps are quite small in magnitude, but it is definitely needed for P.

**Comment by borisbstyle** [comment]
I think the values should be as they really are. 0.018 should not be 18.

I will see to modify this soon if someone else doesnt.
Op 19 jul. 2015 20:08 schreef "zenman8269" <notifications@github.com>:

**Comment by zenman8269** [comment]
It looks like if you set p_rollf = 0.750 by CLI, PID tuning tab still shows 0.8 and any subsequent saves will not effect the 0.750 setting. That is good :)
Subsequent saves in EZ Gui does change it back to 0.8 though. :(
That's going to be annoying!

**Comment by borisbstyle** [comment]
I checked the code and this isn't straight forward as things are being multiplied from the MSP etc....

Pff .......who did ever chose to do it this way

**Comment by Yamaford** [comment]
So inflight tuning steps will need an option to count in smaller steps now too.

**Comment by borisbstyle** [comment]
yes for luxfloat it may be needed
Op 30 jul. 2015 07:12 schreef "Yamaford" <notifications@github.com>:

**Comment by Yamaford** [comment]
Why didn't this make it into the new version?

**Comment by tracernz** [comment]
The way open-source works is if you want something you identify it(done with this issue), write the code, test it, and submit a patch. Nobody did the last 3 steps. ;)

**Comment by Yamaford** [comment]
Actually it has been written and I've been using it for a couple months now but I couldn't find the PR . I see Boris closed it for some reason. https://github.com/cleanflight/cleanflight-configurator/pull/223

**Comment by tracernz** [comment]
Sorry. For whatever reason the commit(s) didn't mention this issue then..

Sent from Outlook




On Thu, Nov 12, 2015 at 9:05 PM -0800, "Yamaford" <notifications@github.com> wrote:
Actually it has been written and I've been using it for a couple months now but I couldn't find the PR . I see Boris closed it for some reason. https://github.com/cleanflight/cleanflight-configurator/pull/223

---

**Comment by LVNeptune** [comment]
I'm confused because the current configurator still only shows one decimal place for P. Am I missing something?

![image](https://cloud.githubusercontent.com/assets/6668449/12074487/e5c8281c-b10b-11e5-93b8-c5f9c631d09c.png)

**Comment by borisbstyle** [comment]
It is still not implemented
Op 2 jan. 2016 13:47 schreef "LVNeptune" <notifications@github.com>:

**Comment by LVNeptune** [comment]
Why is @Yamaford claiming he is using it then..?

**Comment by borisbstyle** [comment]
he used my outdated beta old configurator version. I believe hydra wanted a
cleaner approach for that.
Nobody ever picked it up though. But there are some new discussions going
on to solve it.
Op 2 jan. 2016 14:31 schreef "LVNeptune" <notifications@github.com>:

**Comment by waltr1** [comment]
The latest BetaFlight firmware (2.6.x) has changed the LUX PID scaling.
This should take care of the problem opened in this issue.
See the ßF Wiki and Release Notes.

**Comment by skaman82** [comment]
closing this since luxfloat scaling has changed
