### ISSUE TITLE
Development Documentation

### ISSUE THREAD

**Issue by nathantsoi** [cleanflight/cleanflight-configurator#225]
Maybe this is a sill question, but how do folks develop on this? Do you leave a board plugged in? Maybe there is an emulator or dev mode I missed?

Any advice would be great.

**Comment by thenickdude** [comment]
Currently a board must be plugged in, although I think there is another issue open about writing an MSP emulator that'd emulate a board (to allow a "demo mode" to be supported).

I bought a spare Naze to leave on my desk so I always have one available for testing.
