### ISSUE TITLE
Allow CLI tab access (only) for old firmware revisions

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/cleanflight-configurator#23]
Every time there is a forced Cleanflight Configurator update which breaks compatibility with the old firmware, a good percentage of users can't recover their old board settings to migrate them to the new firmware. In this situation it would be nice if at least the CLI tab still worked in the Configurator, so users could be directed to "dump" on their old firmware using that, flash the new firmware, then reload their configuration and double check if anything didn't port across.

**Comment by hydra** [comment]
yes, i had the same thought today too!

**Comment by Roeland54** [comment]
added in v0.59.1
