### ISSUE TITLE
Backup button  problem on dev branch

### ISSUE THREAD

**Issue by flagadajones** [cleanflight/cleanflight-configurator#231]
The backup button doesn't work on dev branch

**Comment by twokaff** [comment]
Still not working on dev branch, checked out today.

**Comment by robustini** [comment]
Same here with GUI 0.65, only Restore work.

**Comment by howsTricks** [comment]
Confirmed again on 0.66, I don't see any errors logged in chrome debug console so this is above my head :D

**Comment by AustinSaintAubin** [comment]
Currently in GUI 0.66, FW 1.10.0.
Seems like backup button does not function when the mixer is set to one of the new mixes, like custom airplane.

**Comment by hydra** [comment]
Fixed in 7bf70092d35f9e96d1b681c3cc1cda2450049098
