### ISSUE TITLE
Servo page shows incorrect values and not able to save

### ISSUE THREAD

**Issue by lkaino** [cleanflight/cleanflight-configurator#238]
The servo page in current Cleanflight configurator master is not compatible with the Cleanflight master.

The MSP_SERVO_CONF command expects 7 bytes of data (min, max, middle, rate). Cleanflight puts the whole servo config in the reply (min, max, middle, rate, angleAtMin, angleAtMax, forwardFromChannel, reversedSources).

Configurator uses a separate MSP_CHANNEL_FORWARDING command to read the forwardFromChannel parameters for servos. To me it seems Cleanflight does not even support this command.

The configurator should read the channel forward + other servo config from the reply to the MSP_SERVO_CONF command.

I did not check the writing part but I bet it has similar issues.

**Comment by fftunes** [comment]
Noticed that too. Luckily for me it's only the roll-servo channel. I could still use my camera tilt servo, although not being able to save servo range is a bit sketchy.

**Comment by sppnk** [comment]
As I use airplanes now I had to change back to 1.8.1, because configurator in 1.9.0 can setup the rates of ailerons or anything. Hope it could be fixed soon.

**Comment by sppnk** [comment]
![cleanflight servo](https://cloud.githubusercontent.com/assets/12456418/9653639/1c6e6020-5225-11e5-988d-8381d93c7d0e.gif)

Hi, this weird values is what I get in tab servos page. I'm trying to use the last experimental digitalentity fixed-wing version. Anybody knows where to find info on "servo" CLI command? Does "servo" command work in 1.10 or have I to use "smix" command? 

The documentation says "smix" only can be used with CUSTOM mixes, so if I use AIRPLANE mix I am unable to configure my servos with CLI

**Comment by MauroMombelli** [comment]
seems like the configurator use the new servo protocol i proposed, BUT cleanflight use a (better) variation of it.

i'm fixing it right now

**Comment by MauroMombelli** [comment]
fixed in https://github.com/inkonova/cleanflight-configurator/tree/tilting-1.10, see msp.js and servo.js (sorry it is mixed with tilt-arm code, but that shouldn't be a big issue)

**Comment by hydra** [comment]
Please check latest firmware against latest development configurator.  If there are any issues please update this.

**Comment by lkaino** [comment]
Servo page is working on 0.66 configurator, thanks!
