### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by spudym** [cleanflight/cleanflight-configurator#245]
My cleanflight configurator has a message saying that it is not the latest version, 0.65.0 but cannot find a newer version.
Could this be also why I cannot connect to my naze32.

**Comment by twokaff** [comment]
It's a message that appears if your configurator is older than 60 days.  The current release version of the configurator is still v0.65.  It's just a log message and doesn't stop you from using the configurator.

As for the reason why you can't connect to your Naze32, I don't know.  You'd have to be more specific, i.e. an error message from the log window.
