### ISSUE TITLE
Suggestion - add the 3D throttle midpoint setting to the configuration tab

### ISSUE THREAD

**Issue by BlakeFPV** [cleanflight/cleanflight-configurator#247]
Quick suggestion / request for the next version of the CleanFlight app - include the 3D throttle midpoint setting to the configuration tab under the other throttle settings - currently it is only available in the CLI. More pilots are trying out 3D now, and this is a critical setting to keep the motors from spinning when disarmed or when fail safe is triggered.

**Comment by NightHawk32** [comment]
@BlakeFPV thaks for your feedback.
This was added with 31cd2de3d38e95439c56f932a51a8c54b0cf2335
![3d_settings](https://cloud.githubusercontent.com/assets/12000065/12042507/1ccd2b9c-ae7c-11e5-92c9-60fb8b352da7.JPG)

**Comment by BlakeFPV** [comment]
Nice! Thanks for considering this, and all the great work that you guys do!

Date: Tue, 29 Dec 2015 13:33:07 -0800
