### ISSUE TITLE
Stealing skills > Programming skills

### ISSUE THREAD

**Issue by cTn-dev** [cleanflight/cleanflight-configurator#25]
You obviously have no clue how to operate the configurator from developer side since you failed numerous times to deal with something so simple as version expiration dates which i implemented to help inform people with broken googleupdate, this check was implemented to help/inform people about potential problems, its not there to create confusion by your misuse.

Not counting the failure you made with keeping my analytics ID in your fork, at least god damn look what the hell are you pulling as i don't have all day to deal with issues that are created by your laziness and incompetence.

https://github.com/cleanflight/cleanflight-configurator/blob/master/js/review.js#L106
https://github.com/cleanflight/cleanflight-configurator/blob/master/js/review.js#L117

Learn to read damn licencing that is included in svg artwork files that you blindly pull with no regard to original author/s

https://raw.githubusercontent.com/cleanflight/cleanflight-configurator/master/resources/motor_order/quad_x.svg
https://raw.githubusercontent.com/cleanflight/cleanflight-configurator/master/resources/motor_order/quad_x.svg

Same goes for exported blender models that are used with the threejs

https://github.com/cleanflight/cleanflight-configurator/blob/master/resources/models/quad_x.json#L5
https://github.com/cleanflight/cleanflight-configurator/blob/master/resources/models/tricopter.json#L5

Happy holidays.

**Comment by triolus** [comment]
To: ctn-dev
  Just trying to figure out what your saying in your written statement. First is a configurator like programming language for people to write software? And if it is, you make peoples software (forcing them) to have an expiration date on their work?

Wow
Razor

**Comment by tracernz** [comment]
![Wow...](https://i.imgur.com/phukS4d.gif)
