### ISSUE TITLE
Indicate mutually exclusive features better

### ISSUE THREAD

**Issue by pfriedel** [cleanflight/cleanflight-configurator#252]
Features that are mutually exclusive should be more like HTML radio buttons - for example either softserial _or_ led_strip.  Right now the configurator permits you to select both and then reverts when it realizes the options are exclusive.

(that's probably the big obvious one, but there may be others)

**Comment by hydra** [comment]
@pfriedel it's target dependent.  e.g. on a Naze32 that is the case but on an SPRacingF3 you can use SoftSerial and LED Strip at the same time.
