### ISSUE TITLE
Suggestion: new GUI for configurator. Interested?

### ISSUE THREAD

**Issue by skaman82** [cleanflight/cleanflight-configurator#256]
Hi there! I' using cleanflight almost 6 months now (since I am in RC) and I love what you guys put together here but I'm seeing some things that could be improved. I am a graphic designer and work in a advertising agency. In last 10 years I've worked on a bunch of different web-projects an learned a lot about UI & UX Design.

From my point of view CF is great but is becoming more and more complicated to use as new features coming in. Some things are even just in the wrong place or not have correct labeling that a normal user understands without going through docs. It just looks like it was made by developers for developers but not for a normal folks like me. The lack of documentation is another problem.

I would like to develop a new interface for the GUI and cautiously asking if anyone is interested in this before I start. Especially @hydra . It makes no sense to put a tremendous amount of work in this if no one is interested in implementing this. I have no clue about programming and need some help understanding all effects that each input field has on the configuration. From my work I also know that you can't make everybody happy and some of the community will most likely don't like my approach. But we can discuss things of course :)

My goal is not just make the GUI nice and shiny but also complete rethink its structure and functionality. The are talks about removing the CLI. I think this is a good thing, but the GUI needs some more fields for configuration that are not there yet (where can I put in a mag_align value when the CLI is gone?)

Here some examples of my thoughts on improving things:
• There should be just one way to backup the full configuration and all profiles with the backup button - not using CLI
• Profile select field seems out of place. It affects way more just the PIDs so why is this in the PID tab?
• PID Setup is very messy. Each controller uses different variables for different things but the fields are labeled the same on each controller. Good example for that are the LEVEL PIDs which are not realy PIDs. 
• There should be a kind of tooltip for each field with a short description what this value does and the used variable name (if CLI is still there). 
• There should be only hardware specific fields - so if no baro and mag are present there should be no ALT and MAG PID fields in the PID tab to make the interface cleaner. 

I can't put a time frame on this yet but I'm guessing this will take some months to accomplish. So if someone is interested to take the configurator one step further please let me now. I can provide PSD files and all icons as SVG files to work with for final implementing.

**Comment by scooper1** [comment]
I think this would be a good idea 
It would be nice to see a better way of seeing what option combinations can be used for each type and revision of board 
Getting rid of the cli asap and the semi hidden options it brings would be good  maybe a experimental tab to hold untested new options

**Comment by skaman82** [comment]
This is a quick idea how the interface could look like
![cf0](https://cloud.githubusercontent.com/assets/11768024/10553643/e202d93e-745c-11e5-86d7-304b54165aaa.jpg)

**Comment by skaman82** [comment]
Reworked the first screen a bit and developed another version with alternative navigation. I hope you like it. I'm waiting for @hydra to comment on this. If there is no requirement for a better UI yet so be it.

![cf0_a](https://cloud.githubusercontent.com/assets/11768024/10559696/78f666a4-74f7-11e5-99a1-9b3f87daa8f4.jpg)
![cf0_b](https://cloud.githubusercontent.com/assets/11768024/10559699/7cb6040c-74f7-11e5-8506-a55d21658b36.jpg)

**Comment by jarno83** [comment]
Nice :)

**Comment by skaman82** [comment]
Here a possible concept of the GPS Tab with integrated waypoint interface. Maybe this is interesting for @digitalentity who is working on Waypoints in his NAV Rewrite. 
![cf0_gps](https://cloud.githubusercontent.com/assets/11768024/10561343/e23366a8-7524-11e5-9dce-c99dd6376c39.jpg)

**Comment by enly1** [comment]
To me these look great - but one quick question - where did the icon packs etc come from - you been busy with editing tools or were these from an existing icon pack.  If the later, are the Creative Commons / Open Source ?

**Comment by skaman82** [comment]
I made most icons myself. The other come from http://www.flaticon.com. I can redo them by myself later if necessary.

**Comment by enly1** [comment]
All I can say is great work - love everything about the layouts.  If cleanflight choose not to use them, please release them for use with other projects - I'm sure people would greatly benefit (hint: me :-))

**Comment by skaman82** [comment]
Thank you, we see what hydra thinks

**Comment by digitalentity** [comment]
@skaman82 
Absolutely awesome! I love the design. Please also consider the full parameter list similar to [APM Planner](http://diydrones.com/forum/topics/arducopter-3-0-ready-for-wider-use?commentId=705844%3AComment%3A1303976). I believe CLI would at some point dropped in favor of something like this.

**Comment by skaman82** [comment]
@digitalentity
Thank you. I'm not using APM so it would be helpful if you can clarify. What do you mean by "full parameter list"? Could you provide a screenshot of that area in APM? I'm actually searching for good concepts for adding waypoints, especially in mobile apps where you can setup a mission with few touch commands. I think this has to work easy without having to set a bunch parameters.

**Comment by digitalentity** [comment]
@skaman82 
Here is a screenshot of full parameter tree in QGroundControl (APM planner looks similar)
![changed_onboard_parameter](https://cloud.githubusercontent.com/assets/11059099/10563648/6fb3beb0-75d4-11e5-8fe2-b20624419fb7.png)

I'm thinking of this as a generic way of accessing all possible parameters in similar way we do through CLI. There should be an MSP counterpart inside the firmware, but that shouldn't be a problem. If such interface will appear CLI can be removed.

**Comment by skaman82** [comment]
@digitalentity
You mean all parameters inside NAV, right? Could you tell me what each parameter does? Is this necessary to integrate in each waypoint or it is a global setting? NAV_PARACHUTE_EN IMO doesn't sounds like a necessary parameter.

**Comment by digitalentity** [comment]
I'm talking about all parameters inside the flight controller. Literally **everything** that could be read or set by CLI or MSP.
There was a short discussion here: https://github.com/cleanflight/cleanflight/issues/922#issuecomment-141944259

**Comment by skaman82** [comment]
ok, i think now I get it. You are not talking about waypoints, right? You suggesting to add a new tab with a parameter browser like in your screenshot, right?

**Comment by digitalentity** [comment]
Exactly! I'm talking about all accessible parameters. If you can do it in
configurator, I'll create a flight controller counterpart for this.

-- 
Sent from Gmail Mobile

**Comment by skaman82** [comment]
All I'm doing is the design concept for The UI. I'm searching for someone who can actually integrate this design and functionality in the configurator app.

Von meinem iPhone gesendet

**Comment by skaman82** [comment]
I can do a mockup of the parameter browser. Would it be possible to also show the min, max an default values for each parameter and maybee a short description like in cli docs?

Von meinem iPhone gesendet

**Comment by digitalentity** [comment]
Min and max - no problem, default - I don't think so. Default is set in the config code. For some parameters there is no default value (i.e magzero).

Parameter name and description should be stored inside configurator. Firmware should expose only IDs to keep footprint small enough and the configurator will have a mapping table, i.e. parameter 0x01000045 = "PID_ROLL_P"

**Comment by scooper1** [comment]
Showing default values is a good idea. for values without default a blank field is a good indication of no default 

Sent from Yahoo Mail on Android

**Comment by skaman82** [comment]
@digitalentity 
This is how it could look like. The default value could be stored in configurator also.
![cf0_advanced](https://cloud.githubusercontent.com/assets/11768024/10564525/f8b7f82e-75b7-11e5-8591-a2f7e57af227.jpg)

**Comment by skaman82** [comment]
Here some thoughts on backup functionality
![cf0_backup](https://github-cloud.s3.amazonaws.com/assets/11768024/10566052/8b9c7de4-75dc-11e5-8583-e82cd8937921.jpg)

**Comment by tracernz** [comment]
@digitalentity A perhaps more user friendly impelementation (enum type fields have a dropdown with all possible values, units are shown, drop-down trees, only objects relevant to the connected board are shown, filter to search fields etc.):
![screenshot from 2015-10-19 08 23 11](https://github-cloud.s3.amazonaws.com/assets/9995998/10566122/b3a9241e-763a-11e5-990d-b32bae557a9f.png)

**Comment by skaman82** [comment]
@tracernz IMO: dropdown menu would be not so much user friendly on PIDs where we have every large amount of steps or in case of large numbers like in max_angle_inclination. The search field is a great idea though!

**Comment by digitalentity** [comment]
@skaman82 looks excelent to me! Defaults are firmware dependent, but I have thoughts on how to implement them.
Search field as a great idea, but dropdown menus are a bad idea in general. However for some specific settings it might be a good idea - settings like "used PID controller", integer settings with 0 and 1 range (essentially a boolean flag)

**Comment by tracernz** [comment]
@skaman82 Of course the dropdown fields are only for enums as I said! The boxes for integrals or floats are just boxes. The dropdown tree is much nicer to find stuff rather than one big list of variables.

**Comment by skaman82** [comment]
@tracernz 
Have reworked the tree layout a bit. Added: 
• more depth (if necessary) 
• filter at the top 
• dropdown

![cf0_advanced](https://cloud.githubusercontent.com/assets/11768024/10571827/06d7f2de-7643-11e5-9b3e-431f27378d84.jpg)

**Comment by skaman82** [comment]
@digitalentity 
After I thought about the GPS tag for a while I decided not to mix up GPS and waypoint management (when it maybe comes in the future). GPS tab should only about monitoring and maybe debugging. Now I did a separate tab for Waypoints and added some global Mission parameters, do you think this makes sense? And if it does which parameters cold be actually helpful?

![cf0_gps_new](https://cloud.githubusercontent.com/assets/11768024/10576157/7b2ec4f0-7661-11e5-9927-e9c23495c8a0.jpg)

![cf0_mission](https://cloud.githubusercontent.com/assets/11768024/10576162/8364761a-7661-11e5-9400-fe0ba193c39d.jpg)

**Comment by digitalentity** [comment]
@skaman82  Looks great! A separate mission screen is definitely a good idea. Another suggestion would be a mission load/mission save button, so one can design a mission at home, go to the flying field and upload the mission without having to select all the waypoints again. What do you think?

**Comment by skaman82** [comment]
@digitalentity DONE :)
![cf0_mission](https://cloud.githubusercontent.com/assets/11768024/10576774/2d97ebf4-7666-11e5-9e94-a46edb550e3d.jpg)

**Comment by digitalentity** [comment]
Great! I'm so loving your design :+1: 
I wish I knew Java so I could write this myself!

**Comment by skaman82** [comment]
Yeah, I'm really hoping that somebody can make this happen. I think it is not to difficult to apply the UI. Its basically just html/css with some jQuery effects. The functionality is a whole other thing...

**Comment by skaman82** [comment]
Got a bit carried away with layouts for new exiting functions like parameter browser and waypoints, will now focus on tabs that are actually there :)

**Comment by skaman82** [comment]
My first shot at the configurations tab. Running out of space in my layout. Doing this in full size later. Any feedback? 
![cf0_config](https://cloud.githubusercontent.com/assets/11768024/10602771/9d305ff0-771a-11e5-8ee2-154bea0233d3.jpg)

**Comment by skaman82** [comment]
The "Edit custom mixer" Button could show a modal window with functionality like this: http://www.iforce2d.net/mixercalc/

**Comment by skaman82** [comment]
@ledvinap @Pierre-A @borisbstyle @ProDrone Hi guys! I see you constantly work your ass off by improving cleanflight and fixing issues. I'm very grateful that you are putting so high amount of your time in that. I don't know if you are watching the configurator branch or not. I would very appreciate if you could take a quick look at my posts here and tell me what you think. Is it possible to achieve my proposal? I think cleanflight and many users would benefit from it. I don't mean the tons of new functions in my layouts – just the change of the styling of the configurator UI as a start. The new functions can maybe follow later if they make sense. Thanks!

**Comment by borisbstyle** [comment]
@skaman82 Why dont you make a PR of this configurator version? I think Cleanflight UI needs to be renewed :dancer:

**Comment by skaman82** [comment]
@borisbstyle I'm just a designer and have no coding skills, so this is just happening in Photoshop at this state.

**Comment by borisbstyle** [comment]
@skaman82 Why not try integrate it into configurator :D

**Comment by skaman82** [comment]
I could make the basic CSS for all used elements.

**Comment by skaman82** [comment]
After a have all tabs finished in photoshop I will upload the resource PSDs and start to create CSS templates for each tab or area of the interface as far I get with my basic skills. In some places I will have to use placeholder images. From there on someone has to take over and integrate this into configurator. I can supervise from visual point of view and test things.

**Comment by skaman82** [comment]
Here the full configuration tab. Some thoughts on this:
• This is actually one of the messiest tabs (from a designer point of view) and it is hard to keep so much information clean. 
• Renamed large amount of field labels. IMO the description what a feature actually does is more important user information that the CLI name. Thats why I put the description first.
• Placed notes above the inputs to match direction of reading.
• Reworked the QuadX picture to match the color scheme.

![config full](https://cloud.githubusercontent.com/assets/11768024/10617518/4b48e756-776b-11e5-95c0-bc30c068b020.jpg)

**Comment by ProDrone** [comment]
I am not a GUI programmer, but totally love the stuff you design. So much that i am tempted to go there...

**Comment by skaman82** [comment]
@ProDrone thank you. More exiting stuff is coming. Would really love to see this getting out there for people to use.

**Comment by skaman82** [comment]
Do the Ports tab next. Try to take "IO - Cleanup timer/pin allocation #357" in consideration as a additional feature. Still not certain how the logic could be on the GUI side. Ideas? @ledvinap

**Comment by skaman82** [comment]
Moving the project here: https://github.com/skaman82/CF_GUI

**Comment by tricopterY** [comment]
I love the concept, but getting all of that working in concert with the background code is a fair bit of effort.
The Configuration Window looks cluttered. You may consider sliding-down windows for each group/panel?

**Comment by skaman82** [comment]
@tricopterY Thanks für the feedback! I now that fancy stuff like parameter browser or waypoints is far away yet. That was just for fun. :) The first step would be to implement the design in the actual state of configurator and to add some small features like global profile switch or in gps tab a google map that shows the current GPS location if there is a internet connection and we have a fix. I think that is not so difficult for skilled people. I started to dig in the code an change some things but I can only do the CSS. I came across some problems already with JS. Have no clue about JS and need some help: https://github.com/skaman82/cleanflight-configurator/issues/1

**Comment by tricopterY** [comment]
It's great to see an enthusiastic discussion, but unless @hydra (the project owner) endorses the concept, you cannot advance beyond everyone just voicing an opinion. @hydra must have his own good reason(s), for not participating. No one wants to see another variant of something that works reasonably well, just for some L&F change. Please do not get disheartened as this is the very nature of Open Collaboration, and no one should feel getting voted down.:smiley:

**Comment by enly1** [comment]
And in exactly the same way, forks are produced when people have different
views of what would be beneficial to the community - isn't that how
cleanflight came about in the first place?

So while @hydra is the maintainer and has done a great job of taking
cleanflight and the configurator forwards and maintaining a clean code base
with well managed merges, it should not stop people pushing ahead with
updates that they think will benefit the community.  If people speak and
prefer this configuration tool, then i'm sure it will get the support it
needs regardless of the back-end.  Obviously it would be much better all
round if everyone agreed and worked towards a common goal, but lets not
kill this because @hydra has not commented or given it his blessing.

So - @hydra, what's your view - as @tricopterY has said, you have been very
quiet on the topic and while we know the cleanflight firmware is where your
focus is, you've usually checked in by now.

**Comment by skaman82** [comment]
@tricopterY Thanks for the advice. The layouts I made are just a concept open for discussion. IMO it would be nice having a configurator that looks better. The current configurator still looks basically like baseflight and reminds me visually more of an excel sheet than of a modern app in some places. Cleanflight is a very great software so why not have a great presentation for it?  We all love nice things, right? :).

For me this is a way for giving back to the project for the fun I had using cleanflight. All I am writing in this issue is my professional opinion as a graphic designer with experience of many web projects. Conception and design of user interfaces is what I get usually paid for and what I love to do. 

I'm also surprised that @hydra still don't comment on this. 

@hydra: I would be very grateful for your thoughts on this. If you don't like it - no problem, but it will be good to know.

**Comment by tricopterY** [comment]
Open Collaboration encourages Forks - but we need the necessary traction, for it to succeed.
@hydra is the prime mover and doing the heavy lifts.:bicyclist:

**Comment by ProDrone** [comment]
There are so many things that need attention from @hydra that it can take a while even if he likes it.
Proposals in the form form of a good pull request, that require a minimum effort to merge, make a good change to get accepted.

Don't make it too fancy or change too much in a first proposal. A good first step may be just a visual make-over without adding new things (which is very tempting). So that the existing code can be used.

**Comment by skaman82** [comment]
That is exactly what I would like to do as a first step. But changing the design alone are still thousands lines of code to review. It requires rebuilding things in some places. It is not my interest to create a new fork of this. I simply couldn't maintain it "under the hood" by the lack of my programming skills. I am far out my comfort zone by even trying to write the CSS myself.

**Comment by digitalentity** [comment]
@skaman82 
Whie @hydra stays silen about this, may I suggest another feature? It would be great to have a wizart to calibrate the receiver (ask user to center all sticks, move them to their maximum deflection to properly set up rxrange feature). For the general idea please have a look here https://librepilot.atlassian.net/wiki/display/LPDOC/RC+Transmitter+Wizard (video from 1:02)

**Comment by skaman82** [comment]
@digitalentity very good idea! noted

**Comment by enly1** [comment]
@skaman82 - wasn't suggesting a fork was the way forwards - really don't want that to happen.  

I was just pointing out that if the worst comes to the worst, its an option.  If we're saying that if @hydra doesn't like the colour scheme or layouts then the whole thing is dead just seemed the wrong answer.  Lots of people have commented saying how much they like it, 

I would love to help, but can't commit the time at the moment.  I'm producing an open source data logger for motorcycle trackday/race use which is going to use a variant of the configurator for its setup/config which was why I commented on making it available anyway (for selfish-ish reasons). This does however mean that at some point I will have a decent handle on all of the configurators ins and outs and the time to help rework this, but need to prioritise my own project first.  

I've found a few cosmetic bugs already which I will backport into the main configurator code but its low on my priority list.

**Comment by JohnOCFII** [comment]
Really impressive!  One of the things that would be great to integrate into any new design is some sort of "tool tips" where if you hover over an area, a bubble would pop up describing what that field was used for.  (Someone had mentioned that tool tips them selves might not be best, as tablet device like iOS have no concept of 'hover' but you get the idea...)

It's funny that in the broader world, Web programmers seem more prevelant than lower-level C programmers, but in this area, it seems more people are comfortable/willing to hack on the firmware C code than to work on the configurator.  I know personally that's true.

**Comment by skaman82** [comment]
@JohnOCFII You can have a look at my layout of the full configuration tab from 3 days ago. I thought of that already :). I've read all feature requests on github regarding configurator an try to consider them all in the concepts.

**Comment by JohnOCFII** [comment]
> You can have a look at my layout of the full configuration tab from 3 days ago. I thought of that already :).

Opps - sorry - I was not exploding the images in the Github comments, and started typing without reviewing the details.  It looks very good!

**Comment by hydra** [comment]
Woooooooooah!  Thats a lot of work youre putting in.  I need to read though all the comments above. No tine right now.. Yes tabs on the left = good.  Not a massive fan of dark themes.personally.  yes consistent save button location = good.

**Comment by tricopterY** [comment]
Not sure if this type of compact view is favoured:
![screenshot from 2015-10-24 18 59 38](https://cloud.githubusercontent.com/assets/10737131/10709627/e018f47a-7a81-11e5-9142-c0bb5d5a2a72.png)

![screenshot from 2015-10-24 18 57 49](https://cloud.githubusercontent.com/assets/10737131/10709637/2643c9ac-7a82-11e5-81f0-b8449444fe05.png)

**Comment by tricopterY** [comment]
Rework of Configuration tab showing collapsible panels. Not sure if this concept is favoured.
![screenshot from 2015-10-25 09 58 43](https://cloud.githubusercontent.com/assets/10737131/10713196/907866d4-7aff-11e5-9161-766970ca5028.png)
![screenshot from 2015-10-25 10 00 49](https://cloud.githubusercontent.com/assets/10737131/10713198/9d4870de-7aff-11e5-9310-3cce9978fc99.png)

**Comment by skaman82** [comment]
@tricopterY Like your idea!

**Comment by skaman82** [comment]
I worked really hard on this last two weeks and managed to do lot of basic stuff already. Some things I can't get done simply by not knowing how. I created a Issue or more a ToDo list with things to do to have the first step ready for the pull request. I have added al "help wanted" label on things I can not do myself. If you have some time please take a look - maybe you guys can help here and there with JS if you want this to get merged some day: https://github.com/skaman82/cleanflight-configurator/issues

**Comment by tricopterY** [comment]
@skaman82  - can you please provide your own designed icon pack for use. I am working in parallel and am incorporating some of your concepts. Please keep things simple to begin with, and do not add unnecessary stuff like theme options etc. Let's get the basics right, first. Thanks.

**Comment by skaman82** [comment]
@tricopterY You can get all necessary files from here: https://github.com/skaman82/cleanflight-configurator I have already made good progress so far. Maybe you can take a look and help with some things on the issue list?

**Comment by tricopterY** [comment]
My quick hack of @skaman82 designs. It may be easier on the eyes. 
I hope @skaman82 does not mind.
![screenshot from 2015-11-03 16 47 52](https://cloud.githubusercontent.com/assets/10737131/10901926/dbcd643e-824a-11e5-9312-987e956b7eee.png)

**Comment by skaman82** [comment]
@tricopterY I don't mind at all. I'm considering also to make a optional light theme, but as a last step when everything else is finished.

**Comment by skaman82** [comment]
The PR for the phase  is ready: https://github.com/cleanflight/cleanflight-configurator/pull/266 Closing this now
