### ISSUE TITLE
ESC configuration on CC3D

### ISSUE THREAD

**Issue by samerhay** [cleanflight/cleanflight-configurator#259]
it's a quadcopter with CC3D.
Three motors require a min throttle value of 1080 to spin, but the 4th one requires min throttle value of 1230.
I managed to calibrate and compensate for this defect when I was using Openpilot.
but now that I want to use cleanflight, I can't get to calibrate the ESC/motors individually.
I have seen in some places the method for calibrating ESCs in cleanflight, but all of them requires disconnecting the battery. The problem is that once you disconnect the battery, the board stops communicating with the computer. In fact, if I don't have the battery plugged in, I can't get the computer the recognize CC3D as a com port.
I would really appreciate if anyone have any suggestion for me.
I was thinking maybe I could set the min value manually in CLI but i couldn't figure out how to do it.
Thanks in advance.
Sam

**Comment by hydra** [comment]
Please use forums for support.
