### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by Arakon** [cleanflight/cleanflight-configurator#272]
Documentation link says "Documentation for 2.1.2" and points to https://github.com/cleanflight/cleanflight/tree/v2.1.2/docs, which doesn't exist.

**Comment by skaman82** [comment]
@Arakon do you have flashed cleanflight or betaflight? Seems to be betaflight.

**Comment by Arakon** [comment]
Indeed. Does the doc link take the CF revision and generate the link from that?

**Comment by skaman82** [comment]
exactly

**Comment by Arakon** [comment]
In that case, not a Configurator issue.
