### ISSUE TITLE
Firmware Flasher Tab: toggle switches issue

### ISSUE THREAD

**Issue by skaman82** [cleanflight/cleanflight-configurator#274]
The new toggle switches are always shown as off on restart, even when the saved state is checked. This can cause trouble if the user cant see what is actually activated on default. This I couldn't solve myself.

<img width="343" alt="bildschirmfoto 2015-11-13 um 00 14 06" src="https://cloud.githubusercontent.com/assets/11768024/11134233/7c54ee20-899b-11e5-9925-95b7c0403bf7.png">

**Comment by skaman82** [comment]
@wanderzell could you maybe have a look at this?

**Comment by tricopterY** [comment]
I guess you have to use something like:
```
 (new Switchery(elem)).markAsSwitched();
```

**Comment by wanderzell** [comment]
Ok I will take a look on this.

**Comment by tricopterY** [comment]
Ok - this is truly a pain and on examination: 
```javascript
Switchery.prototype.create = function() {
  this.switcher = document.createElement('span');
  this.jack = document.createElement('small');
  this.switcher.appendChild(this.jack);
  this.switcher.className = this.options.className;
  this.events = events(this.switcher, this);

  return this.switcher;
};
```
Switchery hides the checkbox and replaces it with a span that creates the L&F.
But does not actually change the checked/unchecked state of the hidden checkbox, i.e setting the checked property does not affect it. I guess have to use setPosition(true).

**Comment by wanderzell** [comment]
@tricopterY are you working on this?
I think I have solved this. And yes it involves attaching separate event handler to switchery to setPosition() manually.

**Comment by skaman82** [comment]
Great news guys! Thanks a lot for looking into this! Just create a PR against current development branch.

**Comment by tricopterY** [comment]
Sorry - I'm not working on this, just poking around. I tried the new code/PR, and it behaves as before. Unless, I am overlooking/missing something.

**Comment by wanderzell** [comment]
@tricopterY "as before" meaning ... not fixed for you or fixed? It went too late yesterday and wasn't able to test it thoroughly - the other places with checkboxes mainly.

**Comment by skaman82** [comment]
Just tested this. So far I see, this solves the problem. Don't see other bugs regarding this.

**Comment by hydra** [comment]
Fix merged, thanks everyone.
