### ISSUE TITLE
Cleanflight hangs/freezes

### ISSUE THREAD

**Issue by rotorheadRPZ** [cleanflight/cleanflight-configurator#276]
I encounter quit a few problems with Naze32 & Cleanflight. Hope somebody can help me out

1. Naze32 can not connect to CF if the Naze32 is powered up via motors or receiver, only on USB it will connect.

2. If the receiver and/or motors are connected after the USB connection, CF hangs.

3. ''Save and Reboot'' after changing settings: Board saves and reboots but CF hangs. First connection must be terminated before reconnecting via USB to continu.

4. Minim OSD won't work. Tried 2 boards, a clone and an original. No data is received from Naze32. I only get to see the welcome text and loading bar. Everything connected in the correct way.

Actions to solve the problems:

1. Reflashed Naze32. No improvement.
2. Reflashed Naze32 with older firmware then reflashed with the laterst stable firmware (full chip erase). No improvement.
3. Latest version of Cleanflight. No improvement.
4. CP drivers reinstalled on Laptop (Windows 8.1). No improvement.
5. All problems occur with 10DOF & 6DOF versions.

**Comment by hydra** [comment]
too many issues for one report. 

 please ask for help on forums first.  once you have found confirmed bugs please post steps to reproduce on the correct issue trackers.
