### ISSUE TITLE
Port configuration sanity check

### ISSUE THREAD

**Issue by covert-** [cleanflight/cleanflight-configurator#281]
When setting Softserial 1 or Softserial 2 at a speed above 19200 there is no warning that it will most likely cause errors.

**Comment by qfather** [comment]
I'm not sure why there is an option to even go above 19200 for softserial.  Unless I'm missing something?

**Comment by JohnOCFII** [comment]
And if someone is going to look into configurator warning logic, perhaps also look to see if both Soft Serial ports are enabled, and warn/disallow settings greater than 9600 baud.
