### ISSUE TITLE
Cant flash SP3

### ISSUE THREAD

**Issue by arrowcircle** [cleanflight/cleanflight-configurator#282]
Hi! I trying to flash my SP3 controller, but always get error
stm32 communication failed, wrong response, expected: 121 (0x79) received: 31 (0x1f)
I set manual baud rate to 256k, but ring no bells.
I tried to short boot pins and flash with no reboot sequence, but still the same.
But I can connect to it and configure. It shows CF 1.10 version, but I cant flash it.
What I doing wrong?

**Comment by qfather** [comment]
Is it a genuine SPRF3 or a Chinese knock-off?

**Comment by arrowcircle** [comment]
@qfather Its definitely China clone

**Comment by arrowcircle** [comment]
Flashed cleanflight with STM32 Demonstrator tool. Now it works great
