### ISSUE TITLE
CLI becomes unusable after 'save' initiates reboot on Naze32 FCs

### ISSUE THREAD

**Issue by jtp755** [cleanflight/cleanflight-configurator#285]
@CradyCopter and I confirmed that the CLI becomes unusable after executing 'save' with Naze32 FCs. 

Changes are saved and the FC is rebooted but the CLI no longer responds to subsequent commands. You have to change to a different tab and then back to enter more commands if needed. Screen shows 'REBOOTINGp'

I tested with Configurator 1.1.0 and Cleanflight 1.10 and Betaflight 2.1.4

**Comment by CradyCopter** [comment]
Thanks jtp755!  Glad to know it wasn't my PC ; )

**Comment by hydra** [comment]
it's because 'SAVE' does a reboot.  Do you have an idea of how the GUI should detect the fact that you're making the FC reboot?  What do you think should happen when it detects it?

**Comment by hydra** [comment]
Adding some code to make it disconnect when 'Rebooting' is received via the CLI.

**Comment by ledvinap** [comment]
@hydra: Just add `save` (and  possibly `reboot`) button to CLI page.

**Comment by ProDrone** [comment]
@ledvinap We always reboot after save for consistency. Disconnecting is not the best option IMO. Normally i just click on another tab to see when the FC is back online. Maybe select the first tab when rebooting?

**Comment by ledvinap** [comment]
`save` button can easily send "save" command and disconnect board .. much simpler than parsing cli output ...

**Comment by hydra** [comment]
i have a solution, committing now.  I think it handles the various scenarious OK for VCP and non VCP boards.

I think a bit of VCP/Non-VCP cleanup is required as in the commit I duplicated some code from the `configuration.js` file.  Likely other tabs that save and reboot all need similar behavior.

**Comment by jtp755** [comment]
Thanks @hydra!

**Comment by hydra** [comment]
Create new issues and reference this if there are issues with the new code.  I tested it ok a couple of F3 boards I have on my desk and it seems to work fine.

**Comment by skaman82** [comment]
Tested with naze rev 5 & 6. Works fine.
