### ISSUE TITLE
Feature request: use baro for descent rate if available

### ISSUE THREAD

**Issue by tigert** [cleanflight/cleanflight-configurator#287]
If barometer hardware is available, maybe we could use vertical speed and throttle together to set a reasonably slow descent rate for failsafe mode to minimize ground impact damage to the quad?.

**Comment by digitalentity** [comment]
Wrong repository to post this issue, should be opened for Cleanflight, not the configurator :)

**Comment by tigert** [comment]
D'oh! Should be more awake :D. Closing and re-opening. Thanks!
