### ISSUE TITLE
Problem with motors test mode switch and dynamically enabling/disabling switchery sliders 

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight-configurator#297]
It doesn't work.

Tried instructions as per the switchery website and issue but to no avail, please investigate.

Basically, if you use an old version of cleanflight that does not support MSP_3D and enable 3D feature the checkbox should never become enabled.

See #233.
See http://abpetkov.github.io/switchery/
See https://github.com/abpetkov/switchery/issues/30
See https://github.com/abpetkov/switchery/releases/tag/0.8.0

See 18fd5d01ec171effb259a4b4689292ad0a0d677c

**Comment by hydra** [comment]
@skaman82 Please address this issue when you can.

**Comment by skaman82** [comment]
I will have a look in the next view days.

**Comment by skaman82** [comment]
Done in #317. Closing
