### ISSUE TITLE
Improve Linux serial port detection

### ISSUE THREAD

**Issue by shuffleznl** [cleanflight/cleanflight-configurator#3]
Have been testing Bluetooth connections with cleanflight.
115K baudrate via wired connection works, 115k doesn't seem to work via BT (whereas other FC's do work on same settings).

Changing BT module (BT4 BLE) to 57K and setting msp_baudrate to 57K works to get connection.
Interface very slow and CLI unusable. Setting cli_baudrate to 57K as well doesn't help.

I've recorded my findings here: http://1drv.ms/ZUqNT5

**Comment by hydra** [comment]
@sguarin manua port selection is done, see latest development branch.
