### ISSUE TITLE
Typos and Inconsistent Spelling in 1.2.0-dev

### ISSUE THREAD

**Issue by qfather** [cleanflight/cleanflight-configurator#301]
Welcome Tab:
* Sponsor hyperlink to www.makeitbuildit.co.uk produces chrome-extension://invalid/

Firmware Flasher Tab:
* If you have lost _comminication_...

Motors Tab:
* Inconsistent use of propeller and propellor in the Motor Test Mode Notice.  Should be propeller.

**Comment by tricopterY** [comment]
@qfather - Please see #298
Thanks for the catch.

**Comment by qfather** [comment]
Nice, that just leaves the URL.

Thanks for the quick fix.

**Comment by skaman82** [comment]
Merged in dev version, closing
