### ISSUE TITLE
UI Improvement: Duplicate Setup page Battery Voltage in Battery Voltage box of Configuration Page

### ISSUE THREAD

**Issue by pfriedel** [cleanflight/cleanflight-configurator#310]
What the title sez - while tuning out any voltage scale errors it seems odd to have to jump back to the setup page to see what the current scale is reading as instead of tweaking the setting, hitting "Save" and having it update on the Configuration page in the vbat configuration section.

Low-rent mockup below:
![cleanflight_-_configurator](https://cloud.githubusercontent.com/assets/1295722/12028699/586cd7e6-ada1-11e5-9ef5-cbde8c774933.png)

The same applies in the Current Sensor box, naturally.

**Comment by qfather** [comment]
I think it's a neat idea.  I added the battery voltage to the configuration tab and created a PR, #311 

One small caveat, the voltage does not dynamically update like it does on the Setup tab.  If you're sitting on the Config tab for a while and the voltage changes it won't show this until you cycle tabs or reboot the FC.

![cf_vbat](https://cloud.githubusercontent.com/assets/2552474/12058507/cacbacf0-af44-11e5-8241-c0b2b0bb80b6.png)

**Comment by tracernz** [comment]
You could setup a timeout to update it periodically instead. ;-)

**Comment by qfather** [comment]
Not sure if _I_ could. ;)

**Comment by hydra** [comment]
Done
