### ISSUE TITLE
set acc_hardware=1 causes configurator to think Gyro is disabled

### ISSUE THREAD

**Issue by LVNeptune** [cleanflight/cleanflight-configurator#313]
Tested with both CF 1.10 and Betaflight installed and the same problem on both. When running that command it disables the accel but disables gyro in configurator as well. Moving quad shows nothing on screen so it thinks it is disabled. If I fire up the quad with a battery I can move it around so the gyro obviously is working.

**Comment by hydra** [comment]
it's a protocol limitation of MSP.  Needs fixing really.

**Comment by silversurfer48** [comment]
ALSO THE HORIZON AND ANGLE MODE ARE NOT COMING UP ON CONFIGURATOR
