### ISSUE TITLE
Manifest File Missing or Unreadable

### ISSUE THREAD

**Issue by JoeMB84** [cleanflight/cleanflight-configurator#329]
While trying to update Cleanflight to its latest version (1.11.0) via the extensions in Google Chrome, I receive this message. Am I missing something?
![cleanflight extension issue](https://cloud.githubusercontent.com/assets/16966097/12691041/74d494ae-c6b6-11e5-9ed1-f4598b18dc8f.jpg)

**Comment by tricopterY** [comment]
You can only update the Flight Control (FC) firmware via the Configurator. You already have the Configurator installed as an extension. So, run that and choose Firmware Flasher and let it load all the available FC board options, and then select your appropriate board, before clicking on Load Firmware (online).

**Comment by JoeMB84** [comment]
Oh, I see. So, this is for an update of the firmware for the FC, not the configurator? Sorry for such a noob question. LOL!
