### ISSUE TITLE
Configuration - Display board pinouts

### ISSUE THREAD

**Issue by casedog21** [cleanflight/cleanflight-configurator#33]
Not sure how feasible this is. I am new to this flight controller and Hydra said to share my experience. 

One item that I think would be handy would be the ability after selecting the controller and flash type, would be either another tab or something where you could essentially mock up your connections and layout.

For example if I am using a Naze 32 , with HEXA motor layout, sonar, and a PPM input encoder, a receiver. 

That I could see a reference diagram of the pinnouts. 

That way there would be a logical reference with the pins in use being numbered or "lit" in the diagram and to help make sure that each motor is connected to the right set of pins.

Maybe even add a link to a manual on the manufactures site for the common items. 

Low priority. Just a thought. Couldn't hurt to ask.

-WhirlyGig

**Comment by hydra** [comment]
yes.

If you can provide high quality images of all the supported boards that would be a good start.

**Comment by sinjens** [comment]
I have Naze32 acro and full, flip32+ and a Quanton controller.  I'll sort out some decent photos of those at least.  I've also got a CC3D, but that is a bit hacked unfortunately ...

**Comment by enly1** [comment]
If someone wants me to photo a cc3d, I have one still in the silver antistatic bag.
