### ISSUE TITLE
Better readability in sun light.

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/cleanflight-configurator#331]
The left side of the CFC (and RFC) has to low contrast in sunlight, I have to cursor around and wait for the popup help to figure out what I am about the select. The main panel is fine in the sun.

Would also be nice to add acro_plus_factor adjustment in the inflight adjustments.

Thanks.

**Comment by skaman82** [comment]
Please check the DEV version. I already made some improvements regarding the menu.
