### ISSUE TITLE
3D model of quad is showing wrong prop configuration

### ISSUE THREAD

**Issue by lblblb** [cleanflight/cleanflight-configurator#332]
The 3D model has props that are all oriented the same way, instead of them showing alternating directions (CW and CCW). I think this could be improved to help newbies.
![2016-02-04 14_45_00-cleanflight - configurator](https://cloud.githubusercontent.com/assets/12690798/12827406/df7c13a4-cb7f-11e5-8801-5e7d2e88d9bf.png)
Maybe also change the coloring around to visualise prop orientation instead of simply differentiating front and back row props.

**Comment by skaman82** [comment]
Is that really so important?

**Comment by lblblb** [comment]
It's not really important, but it might confuse somebody. See it as an improvement request.

**Comment by hydra** [comment]
@Akfreak any change you could update the models?
