### ISSUE TITLE
ARM in Mode tab should give visible danger warning

### ISSUE THREAD

**Issue by timdonovanuk** [cleanflight/cleanflight-configurator#333]
Incorrectly/accidentally setting ARM mode to a aux channel and range that's 'on', will instantly cause props to spin (when MOTOR_STOP is disabled, or even when its enabled, if throttle is up)..obviously this is because the quad has been armed. And this is correct however..

All other actions in Cleanflight that might cause a spin up come with a warning (e.g. the motor page, setting oneshot etc.). This is even more dangerous, as it's not just arming and spinning at low-idle speeds (as with normal stick arming where throttle is naturally at zero), but you're now at the mercy of wherever the sticks of your transmitter are.

Obviously on the bench using Cleanflight I have props off, but not everyone follows this advice, and there is a danger here.

Consider not allowing the user to save the Modes page if a save will result in ARM mode being ON (or at least provide a clear warning).

**Comment by fftunes** [comment]
As long as there's no transmitter controlling the aux channel, it is not possible to accidentally arm by changes on mode page. It automatically avoids the arm range.

Usually with transmitter on, if throttle channel is above min_check, you can't arm. Is this safety feature bypassed when saving changes on mode page? 

Anyway i recommend using a receiver pack and to never power the drive train unless it's needed for calibration or testing.
