### ISSUE TITLE
motor test and 3D mode do not work

### ISSUE THREAD

**Issue by Tanguy59** [cleanflight/cleanflight-configurator#334]
with the 1.2.0 version, impossible to test motors with 3D mode active !
the 1.1.0 works correctly 

Regards
TAnguy

**Comment by tricopterY** [comment]
In Configuration Tab make sure all the 3D Deadband parameters are set correctly, specially the 3D Neutral.

**Comment by Tanguy59** [comment]
it is not the probem.
the problem is with the cursors on motors tab .. 
Cursors motors rest in zero with a middle command! and 3D enable on configuration tab
with the old version 1.1.0 the cursros was on middle range

**Comment by tricopterY** [comment]
What are your 3D-Neutral, 3D-Throttle-Deadband, 3D-Deadband Low and 3D-Deadband High values set at?

**Comment by fftunes** [comment]
Is it maybe the failsafe throttle you are seeing?
