### ISSUE TITLE
Motor 1 and motor 2 test tab nor spining

### ISSUE THREAD

**Issue by BaltasarParreira** [cleanflight/cleanflight-configurator#335]
Hi have this issue, that I only can spin all motors using the Master tab, individual using of each motor only number 3 and 4 works, 1 and 2 don't make the respective motors spin.

Is this an old bug? I had the same issue with previous cleanflight configurator version, the 1.1.0.

**Comment by jsweeney91** [comment]
Have you tried swapping the esc servo leads over? like swap 1 and 3 to see if it's an ESC issue
