### ISSUE TITLE
Vbat Issue

### ISSUE THREAD

**Issue by JoeMB84** [cleanflight/cleanflight-configurator#338]
When enabling Vbat in cleanflight (version:1.2.0) and setting the warning voltage to anything below 3.5 the Flip32+ will emit short beeps (via the piezo buzzer connected the "Beeper" pins of the flight controller) indicating low cell voltage, even if the cells are above the warning voltage. What would cause this?

**Comment by NightHawk32** [comment]
This is not related to the configurator, please create an issue ine the cleanflight repo.
