### ISSUE TITLE
Latest CF GUI not saving Modes to Naze32

### ISSUE THREAD

**Issue by Hands0n** [cleanflight/cleanflight-configurator#34]
From one of our forum members:

"cleanflight cant save modes to my full naze32. Save to the eprom in cleanflight then when I disconnect and reconect one of the flight modes are saved."

I've seen similar reported elsewhere also, but not on here. So here's a potential bug report.

Has something changed or is this a bug?

**Comment by hydra** [comment]
please provide steps to repeat.  Not have any issues here.  Make sure you're running latest stable chrome, firmware, and configurator.

**Comment by hydra** [comment]
Without any further information I can't progress this issue.

Closing the issue.

If you can provide the additional requested information it can be re-opened and investigated.

**Comment by Hands0n** [comment]
Hi Dominic

Will run my own tests and see if I can replicate the symptoms. If i can
then will post details and video for you to review.

Regards
Danny

On 7 January 2015 at 15:06, Dominic Clifton <notifications@github.com>
wrote:

> Closed #34
> <https://github.com/cleanflight/cleanflight-configurator/issues/34>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cleanflight/cleanflight-configurator/issues/34#event-215326553>
> .
>



-- 
Regards
Danny Thompson
