### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by justgook** [cleanflight/cleanflight-configurator#344]
It would be nice feature to allow people write some plugins. Create some easy to use API to be able add new buttons/sections to configurator. First plugin that I see would be blhelisuit just as additional tab in configurator where u can configure or update firmware of Your ESC, by not leaving FC application. 
Other application/plugin could be some custom Flight planer where u can set some path on map, and let drone flight by it self...

**Comment by skaman82** [comment]
Since there is not a single comment in this over a year, I guess there is no real interest in this. I also doubt that that this can be done in a chrome app.
