### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by reiser4** [cleanflight/cleanflight-configurator#345]
see screenshots:

![bug1](https://cloud.githubusercontent.com/assets/2445517/13070921/51f94f46-d490-11e5-8d6b-b46e1feaafcf.PNG)
![bug2](https://cloud.githubusercontent.com/assets/2445517/13070922/53ba64e6-d490-11e5-817b-984c3a6605bf.PNG)

**Comment by skaman82** [comment]
The documentation link is generated dynamically depending on CF version you have flashed. If you use Betaflight or a pre-release version, the link can not work. So it is not really a bug.
