### ISSUE TITLE
In flight dashboard

### ISSUE THREAD

**Issue by Sudo2Me** [cleanflight/cleanflight-configurator#346]
I have a 3DR telemetry radio laying around and would love to use it with cleanflight. However it is difficult to use as one all the information is spread over so many tabs. It would be great if the cleanflight configurator had a dashboard displaying the necessary information during flight, for instance map information next to sensor data, or the 3d model like the one in the setup tab.

The dashboard would give similar functionality as the android app EZ-GUI (http://ez-gui.com/) So it would look something like this:

![image](https://cloud.githubusercontent.com/assets/12884566/13199920/817f0290-d834-11e5-9ed7-f5161e4fcf50.png) (Thanks to@skaman82 for the original picture)

The addition would need barely any new assets as the most of it is already integrated, but spread over multiple tabs. Look at these for instance: https://github.com/cleanflight/cleanflight-configurator/tree/development/images/flightindicators

It would also make cleanflight more competitive with ardupilot which has the following screen. 

![image](https://cloud.githubusercontent.com/assets/12884566/13201854/53a136fa-d883-11e5-8199-39527fee0ee4.png)

**Comment by skaman82** [comment]
Generally a good idea, but for what do we need the instruments and the 3D model?
