### ISSUE TITLE
Documentation link in client is broken

### ISSUE THREAD

**Issue by proggod** [cleanflight/cleanflight-configurator#348]
Documentation link in client goes to https://github.com/cleanflight/cleanflight/tree/v1.13.0/docs which is a 404 error

**Comment by SteveAmor** [comment]
Related to #345

**Comment by skaman82** [comment]
The documentation link is generated dynamically depending on CF version you have flashed. If you use Betaflight or a pre-release version, the link can not work. So it is not really a bug.

**Comment by hydra** [comment]
yeah, i will consider smarter ways if people have suggestions, but @skaman82 is right, it's not a bug.
