### ISSUE TITLE
configurator crashes instantly

### ISSUE THREAD

**Issue by proggod** [cleanflight/cleanflight-configurator#353]
Can someone tell me how to catch why configurator crashes?   On both my surface 3 and my surfacebook it constantly crashes.  If i open up chrome in developer mode, and keep it open eventually after running it over and over i can get it to stay open, and then it works.  But is there a way to detect why it crashes?   It does seem to work fine on my desktop, and my macs.

**Comment by hydra** [comment]
grab the source and install via the 'alternative way' see readme.md.  the the developer tools to try and find the source of the problem.
