### ISSUE TITLE
Unable to set LTM telemetry in Configurator 1.12

### ISSUE THREAD

**Issue by DzikuVx** [cleanflight/cleanflight-configurator#355]
After enabling telemetry output on any serial port (Hardware and Soft) and choosing LTM as a provider, option is reverted to "Disabled" after Save.

Configurator: 1.2
Board: Flip32
Cleanflight: 1.12

Steps to reproduce:
1. Open Configurator
1. Goto Configuration
1. Enable TELEMETRY
1. Save and Reboot
1. Goto Ports
1. Set LTM on 9600 in telemetry on UART2
1. Save and Reboot
1. Telemetry is reverted to Disabled 

Setting the same under EZ-GUI works fine

**Comment by hydra** [comment]
fixed in a924e06c1bd8a28479b4d0ab33086920690ba943
