### ISSUE TITLE
Windows 7 blue screens

### ISSUE THREAD

**Issue by sybaseguru** [cleanflight/cleanflight-configurator#356]
I'm fine running configurator on Ubuntu 14.04 on a desktop, but both my laptop and desktop crash when running windows 7 version of configurator.

I get connected ok, and can sometimes use it for minutes normally until it blue-screens. It seems completely random as to when it crashes, sometimes seconds into a session, sometimes several minutes, always doing different activities, never the same twice.

Unfortunately blue screen doesn't stay up long enough to read it.

I've reinstalled drivers and have latest cleanflight firmware running on full afroflight32 rev 6

Any suggestions?

**Comment by hydra** [comment]
nope.  probably something wrong with your OS or hardware.  Odd that you have the issue on two machines.  what's common between them.

doing a fresh OS install on one of them, adding the configurator and verifying it.  without more info there is nothing we can do, closing the issue.
