### ISSUE TITLE
Receiver Calibration Function

### ISSUE THREAD

**Issue by ethomas997** [cleanflight/cleanflight-configurator#359]
It'd be good if there was a receiver-calibration function in the configurator, like what is in the ArduPilot MissionPlanner.  It could make use of the 'rxrange' commands to set values.  Anyone else interested in this?

--ET

**Comment by hydra** [comment]
yes

**Comment by hydra** [comment]
however you'd need to be able to get hold of the RAW RC values, and not the ones that are displayed on the receiver tab as the rxloss / failsafe code will set those when the rx input is bad.
