### ISSUE TITLE
throttle middle value in the config tab

### ISSUE THREAD

**Issue by waltr1** [cleanflight/cleanflight-configurator#365]
The throttle middle value in the config tab is incorrectly labeled.
This is the MID_RC value applied to ALL stick input values. I checked this by changing it in the GUI then checking in the CLI.

This has caused much confusion to beginners and experts alike.

The label in the GUI should be changed,

Or move this parameter to the RX Tab since it is the value that CF expects as the stick centers.

**Comment by gaelj** [comment]
This did get me wondering why my quad was drifting when changing this value, but then it does say [RC inputs center value] as well as Mid Throttle, so it didn't take long to figure out what was going on.
I suggest just keeping RC inputs center value, or possibly, All RC inputs center value.
