### ISSUE TITLE
Configure ESC parameters directly

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight-configurator#375]
https://github.com/cleanflight/cleanflight/pull/2075 and https://github.com/cleanflight/cleanflight/pull/2090, it is easy to implement 4way interface over MSP.

With it, it would be possible  to configure ESC parameters directly from configurator.

Is there someone who can work on configurator part? I can implement firmware support.

**Comment by 4712** [comment]
I have thought about, but I'm afraid, my coding style is not cleanflight compatible...

**Comment by ledvinap** [comment]
@4712 : Sorry, I didn't mean to offend you. I wanted to redesign the entry from MSP only. But it got out of my hand a bit..

**Comment by skaman82** [comment]
@ledvinap I can help you out with the GUI layout and html/css - with the JS someone else has to take over

**Comment by DieHertz** [comment]
Do we really need to redesign anything? My idea is to do all the work in CleanFlight Configurator, say add  a built-in "BLHeli Configurator" limited in terms of supported interfaces.
We basically have to implement a part of BLHeliSuite functionality, allowing to at least read/write EEPROM and map all the settings.
I can do the JS and C++ (if required) parts, you can help me with the presentation layer. I'm currently figuring things out in my local repo, will check back in later.

**Comment by DieHertz** [comment]
I'm currently working on it in my own repo. Suggestions about GUI are highly desired and appreciated.
Are we going to mimic BLHeliSuite by displaying all available settings, or some restricted subset of them? What about different modes? I suggest initially supporting only MULTI.
