### ISSUE TITLE
1.2.2 crashing Win10_32bit

### ISSUE THREAD

**Issue by PopPopFPV** [cleanflight/cleanflight-configurator#387]
I'm trying to finalize programming on SPF3 board to run Flysky iBus and LED strip.
CF v 1.2.2 crashes erratically. Tab switching, save settings, highlight functions. Doesn't matter.
I can work for 2 minutes or 3 seconds. But it always crashes.
Win10 reports a BSOD kernel error and reboots.
Running as Administrator. 
Will try on my 64bit box soon.
Any ideas or suggestions?

Thanks
- Mike

**Comment by hydra** [comment]
no very odd.  I have it running fine on a win10 32bit tablet which I use in the field all the time, never crashed.  suggest upgrading all your drivers.  Gonna close this as there's nothing else we can do without more information (crash logs, etc).
