### ISSUE TITLE
Self Test Mode for Gyro / ACC. - Feature

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/cleanflight-configurator#389]
Why not add a self test feature to the gui. It would be nice to be able to test after crashes, new boards, etc.

Also would be neat if it could check for noisey gyros, if it could be sensitive enough to see the 6500 gyro is more noisy over the other gyros, maybe on a graph with numbers.

From the MPU6000 datasheet.
7.12 Self-Test
Please refer to the MPU-6000/MPU-6050 Register Map and Register Descriptions document for more details on self test. Self-test allows for the testing of the mechanical and electrical portions of the sensors. The self-test for each measurement axis can be activated by means of the gyroscope and accelerometer self-test registers (registers 13 to 16). When self-test is activated, the electronics cause the sensors to be actuated and produce an output signal. The output signal is used to observe the self-test response. The self-test response is defined as follows: Self-test response = Sensor output with self-test enabled – Sensor output without self-test enabled The self-test response for each accelerometer axis is defined in the accelerometer specification table (Section 6.2), while that for each gyroscope axis is defined in the gyroscope specification table (Section 6.1). When the value of the self-test response is within the min/max limits of the product specification, the part has passed self test. When the self-test response exceeds the min/max values, the part is deemed to have failed self-test. Code for operating self test code is included within the MotionApps software provided by InvenSense.
MPU6000 datasheet link:
https://www.cdiweb.com/datasheets/invensense/MPU-6050_DataSheet_V3%204.pdf

**Comment by hydra** [comment]
good idea, but needs firmware support first.
