### ISSUE TITLE
Spektrum satellite problems on naze32 v6

### ISSUE THREAD

**Issue by Austinthemighty** [cleanflight/cleanflight-configurator#391]
When i configure cleanflight to use RX_SERIAL it it dose not save it for some reason, also when i do dump it shows RX_PPM

**Comment by Austinthemighty** [comment]
Update:  when i flashed baseflight i was able to use the RX_SERIAL feature.

**Comment by Austinthemighty** [comment]
ok so the problem was that i did not set up serial rx on uart2 first, it would be a nice addition if when selecting serial rx on the configuration page a pop up would say to do that

**Comment by skaman82** [comment]
this should help: https://github.com/cleanflight/cleanflight-configurator/pull/396
