### ISSUE TITLE
Battery voltage scale change

### ISSUE THREAD

**Issue by airmamaf** [cleanflight/cleanflight-configurator#4]
Battery voltage scale should change to take into account the modification linked to this pull request : https://github.com/cleanflight/cleanflight/pull/108

**Comment by airmamaf** [comment]
@hydra, sorry was the late reply, I was on holidays, this was related to the new max value of VBAT_SCALE_MAX, the value of the firmware was different form the one of the gui

**Comment by hydra** [comment]
Done
