### ISSUE TITLE
ARM switch to green every 5-20 pressing

### ISSUE THREAD

**Issue by Jok3r89** [cleanflight/cleanflight-configurator#406]
Hello,
i have many problem s with my FC, what is wrong ? 
The RC Gyro and Accel is adjusted

[[URL=http://www.directupload.net][IMG]http://fs5.directupload.net/images/160702/xcfgdzht.png[/IMG][/URL]](url)

Here are my stats:
Cleanflight Configurator: 1.2.2
# Cleanflight/NAZE 1.13.0 May 30 2016 / 22:43:35 (0245144)
Skyline32 OSD Adv v2

Running - OS: OSX 
Motor: BW2204 -2300 built in ECS 
FrSKY D8R-XP Receiver – Turnigy 9xr pro Transmitter. (PPM)

#get :
looptime = 2000
emf_avoidance = OFF
i2c_highspeed = ON
gyro_sync = ON
gyro_sync_denom = 1
mid_rc = 1500
min_check = 1050
max_check = 1900
rssi_channel = 0
rssi_scale = 30
rssi_ppm_invert = OFF
rc_smoothing = OFF
rx_min_usec = 885
rx_max_usec = 2115
serialrx_provider = SPEK1024
sbus_inversion = ON
spektrum_sat_bind = 0
input_filtering_mode = OFF
min_throttle = 1150
max_throttle = 1850
min_command = 1000
servo_center_pulse = 1500
motor_pwm_rate = 400
servo_pwm_rate = 50
3d_deadband_low = 1406
3d_deadband_high = 1514
3d_neutral = 1460
retarded_arm = OFF
disarm_kill_switch = ON
auto_disarm_delay = 5
max_arm_angle = 25
small_angle = 25
fixedwing_althold_dir = 1
reboot_character = 82
gps_provider = NMEA
gps_sbas_mode = AUTO
gps_auto_config = ON
gps_auto_baud = OFF
gps_pos_p = 15
gps_pos_i = 0
gps_pos_d = 0
gps_posr_p = 34
gps_posr_i = 14
gps_posr_d = 53
gps_nav_p = 25
gps_nav_i = 33
gps_nav_d = 83
gps_wp_radius = 200
nav_controls_heading = ON
nav_speed_min = 100
nav_speed_max = 300
nav_slew_rate = 30
telemetry_switch = OFF
telemetry_inversion = OFF
frsky_default_lattitude =  0.000
frsky_default_longitude =  0.000
frsky_coordinates_format = 0
frsky_unit = IMPERIAL
frsky_vfas_precision = 0
hott_alarm_sound_interval = 5
battery_capacity = 0
vbat_scale = 110
vbat_max_cell_voltage = 43
vbat_min_cell_voltage = 33
vbat_warning_cell_voltage = 35
current_meter_scale = 400
current_meter_offset = 0
multiwii_current_meter_output = OFF
current_meter_type = ADC
align_gyro = DEFAULT
align_acc = DEFAULT
align_mag = DEFAULT
align_board_roll = 0
align_board_pitch = 180
align_board_yaw = 90
max_angle_inclination = 500
gyro_lpf = 188HZ
gyro_soft_lpf = 60
moron_threshold = 32
imu_dcm_kp = 2500
imu_dcm_ki = 0
alt_hold_deadband = 40
alt_hold_fast_change = ON
deadband = 0
yaw_deadband = 0
yaw_control_direction = 1
3d_deadband_throttle = 0
throttle_correction_value = 0
throttle_correction_angle = 800
pid_at_min_throttle = ON
yaw_motor_direction = 1
yaw_jump_prevention_limit = 200
tri_unarmed_servo = ON
servo_lowpass_freq =  400.000
servo_lowpass_enable = OFF
default_rate_profile = 0
rc_rate = 80
rc_expo = 60
rc_yaw_expo = 0
thr_mid = 38
thr_expo = 86
roll_rate = 0
pitch_rate = 0
yaw_rate = 0
tpa_rate = 0
tpa_breakpoint = 1500
failsafe_delay = 10
failsafe_off_delay = 200
failsafe_throttle = 1000
failsafe_kill_switch = OFF
failsafe_throttle_low_delay = 100
failsafe_procedure = 0
gimbal_mode = NORMAL
acc_hardware = 0
acc_cut_hz = 15
accxy_deadband = 40
accz_deadband = 40
accz_lpf_cutoff =  5.000
acc_unarmedcal = ON
acc_trim_pitch = 0
acc_trim_roll = 0
baro_tab_size = 21
baro_noise_lpf =  0.600
baro_cf_vel =  0.985
baro_cf_alt =  0.965
baro_hardware = 0
mag_hardware = 0
mag_declination = 0
pid_controller = LUX
p_pitch = 28
i_pitch = 20
d_pitch = 25
p_roll = 30
i_roll = 20
d_roll = 25
p_yaw = 48
i_yaw = 25
d_yaw = 2
p_alt = 37
i_alt = 15
d_alt = 3
p_level = 20
i_level = 10
d_level = 100
p_vel = 120
i_vel = 45
d_vel = 1
yaw_p_limit = 500
dterm_cut_hz = 0
gtune_loP_rll = 10
gtune_loP_ptch = 10
gtune_loP_yw = 10
gtune_hiP_rll = 100
gtune_hiP_ptch = 100
gtune_hiP_yw = 100
gtune_pwr = 0
gtune_settle_time = 450
gtune_average_cycles = 16
blackbox_rate_num = 1
blackbox_rate_denom = 5
blackbox_device = SPIFLASH
magzero_x = 4096
magzero_y = 2701
magzero_z = 4096
#

**Comment by hydra** [comment]
please use rcgroups for support
