### ISSUE TITLE
ignore :)

### ISSUE THREAD

**Issue by Maxzor** [cleanflight/cleanflight-configurator#416]
ignore pls ...

**Comment by skaman82** [comment]
Hi Max,

You posted this in the wrong branch. You should post your questions regarding betaflight in the  betaflight repo and close this issue here. Or better use rcgroups for questions.

Von meinem iPhone gesendet

**Comment by gaelj** [comment]
@Maxzor can you close this please.

**Comment by Maxzor** [comment]
Sorry and thumbs up for the Cleanflight project even if im willing to help BF atm :)
