### ISSUE TITLE
Special Colors are broken in the LED Tab

### ISSUE THREAD

**Issue by skaman82** [cleanflight/cleanflight-configurator#423]
Special colors are not configurable anymore (greyed out) in the LED tab. Newest configurator (dev branch) and CF 1.13. Tested on spracing F3. Default settings, just enabled the LEDs. Also got some other bug reports about this.

@gaelj do you mind to take a look at this again?

<img width="364" alt="bildschirmfoto 2016-10-05 um 23 23 05" src="https://cloud.githubusercontent.com/assets/11768024/19132300/2b616a92-8b53-11e6-8de9-48b41477f552.png">
<img width="345" alt="bildschirmfoto 2016-10-05 um 23 22 16" src="https://cloud.githubusercontent.com/assets/11768024/19132301/2b8aab6e-8b53-11e6-8f35-1a09c6d0d3f1.png">
<img width="295" alt="bildschirmfoto 2016-10-05 um 23 22 47" src="https://cloud.githubusercontent.com/assets/11768024/19132302/2b91dcc2-8b53-11e6-99a3-eaa38599191f.png">

**Comment by skaman82** [comment]
@gaelj I have just seen your comment on other led issue that you have some time to work on it this weekend. Could you please also have a look on this one? I am not sure how this got broken.

**Comment by gaelj** [comment]
It got broken when we changed some MSP ID's to maintain compatibility with betaflight.
Should be fixed now.
