### ISSUE TITLE
No USB in the drop down menu 

### ISSUE THREAD

**Issue by drone-mechanik** [cleanflight/cleanflight-configurator#424]
I have the latest version Cleanflight (1.2.3) and Chrome (54.0.2840.59 - 64bit) installed on my iMac running the latest Mac OS X  Sierra (10.12). I have installed the CP210x USB to UART Bridge VCP Drivers. I also have tried to force the serial connection using a command line in the terminal. None of the above helped... And I am using a proper data USB cable and not a charging cable.

I've googled around a bit but can't find a solution to my problem? 

If everything is working normally, does the USB port show up in the drop down menu even when there isn't a Flight Controller connected? Or there has to be something connected and powered up in order for it to show in the option? 
I have of course had my FC powered up and connected to my iMac when I was trying to get it to communicate with Cleanflight.

Please help!!! Thanks in advance for all your input!

* it's a TBS Vendetta, with the Powercube, the FC is Colibri.

**Comment by codepreneur** [comment]
I am having exactly same problem. Any ideas?

![image](https://cloud.githubusercontent.com/assets/3421858/19568640/4378a21a-96ea-11e6-88e8-4ae01f73d5ff.png)

**Comment by codepreneur** [comment]
Actually I tried different USB cable and it works!

![image](https://cloud.githubusercontent.com/assets/3421858/19568860/3bbb26be-96eb-11e6-839c-acf6f7248e4f.png)

**Comment by codepreneur** [comment]
The problem is described here: https://www.rcgroups.com/forums/showthread.php?t=2602386 and you can download required drivers here: http://www.silabs.com/products/mcu/pages/usbtouartbridgevcpdrivers.aspx

**Comment by hydra** [comment]
Read the manuals and use rcgroups.com for support please, not here.
