### ISSUE TITLE
GUI backup and restore missing?

### ISSUE THREAD

**Issue by unitware** [cleanflight/cleanflight-configurator#426]
Hi I cannot see the backup and restore options in the configuration view anymore (branch development) is this intentional or an error by me?

**Comment by jtrjr** [comment]
I'm experiencing the same issue. In the "Setup" window there is no longer a backup or restore option.

**Comment by Nokistar** [comment]
Yes me to. I have the same problem.
I also cannot change the minimum trottle... I can't save the change.

**Comment by jtrjr** [comment]
Hey guys, further research by reading the changelog shows that they did away with the backup and restore process in the latest version. Apparently, it wasn't working as it was intended. There also appears to be no way to go back to the previous version. I ended up rebuilding mine from scratch.

Jerry

**Comment by tommyseus** [comment]
Which method is now the best to create and restore backups?

**Comment by jtrjr** [comment]
Tommy,

I don't have any idea. I'm new to all of this stuff. The best I can tell, there is a way to do it from the "CLI" process but I haven't gotten that far. I've been more concerned with getting my settings tweaked so I could get my bird in the air.

Jerry

**Comment by Nokistar** [comment]
Betaflight...

**Comment by hydra** [comment]
backup and restore was killed so that people focus on the RIGHT way of doing backups, which is NOT via the old MSP commands but should be by the new Parameter Groups in the firmware.  They need exposing via MSP, @ledvinap did some work on it in the firmware but it's not done yet.  In the mean time there's no point keeping the old broken code.

**Comment by unitware** [comment]
ok, I see. But is there an open issue regarding this elsewhere? It's an important function that went missing and I'd love to see a discussion thread that synchronizes the work somewhere. The label should be regression I guess?
