### ISSUE TITLE
Newbee question about configurator update 1.2.3

### ISSUE THREAD

**Issue by rodge402** [cleanflight/cleanflight-configurator#427]
Sorry for the last post. I didn't realize the cap lock was on. I don't know how to delete the post so I did this edit. I figured it all out but I want to thank you guys for the reply.

**Comment by Austinthemighty** [comment]
OMG what is with the caps, the 1.2.3 is the configurator and the 1.14.0 is the soft ware that goes on the drones Flight controler. hope this helps

**Comment by rodge402** [comment]
Thanks all for the input
