### ISSUE TITLE
1.2.4 Configurator not showing options for RX Serial or sbus in configuration

### ISSUE THREAD

**Issue by stucarius** [cleanflight/cleanflight-configurator#431]
Not sure what is going on but the Cleanflight configurator is not showing the setup options for RX Serial and sbus. I have done multiple erases and firmware reinstalls including reloading the Chrome App. Nothing is working.

**Comment by WhollyMindless** [comment]
Didn't those options move to the receiver page? (I believe betaflight did it first)

**Comment by Kuschter** [comment]
Wie kann ich den Cleanflight auf eine ältere Version für den Walkera F-210 3d rüsten.
Version 1.2.4 glaube ich.
Finde diese niergends

Gruss Marco
