### ISSUE TITLE
naze32 只有在baseflight  刷2015-5的固件正

### ISSUE THREAD

**Issue by jiekchenid** [cleanflight/cleanflight-configurator#433]
现在的问题是。naze32 只有在baseflight  刷2015-5的固件正常，GPS，电调都正常。。。cleanflight  betaflight 刷完固件都不正常，都不能校准电调，也检测不到GPS,甚至刷他俩最新的固件，都无法校盘罗盘和水平，按钮都是灰色的。是什么原因，校准时电调时，通电，电机总是进入编程模式，是不是因为我的板子太老了。。刷betaflight 刷一个老的固件能校准水平和罗盘，但是校准不了电调，，油门最大，一通电，电机的响声不是校准模式，而是某个编程模式！！！！！GPS也检测不到。。。。。。但刷回baseflight 就一切正常。

**Comment by metalnow** [comment]
老兄，這裡不是幫你查問題的地方，況且你很多細節沒講清楚。這些問題你應該要在5imx上提出才對。
