### ISSUE TITLE
Is it allowed to get the protocol of Configurator?

### ISSUE THREAD

**Issue by ClydeChenT** [cleanflight/cleanflight-configurator#444]
if yes, where can i get it?

**Comment by mikeller** [comment]
Have a look at https://github.com/cleanflight/cleanflight/blob/master/src/main/fc/fc_msp.c .

**Comment by ClydeChenT** [comment]
@mikeller Thanks for your reply, but I don't know the necessary data making Configurator work well my code. For now I just captured these data from USB port. I'm just wondering if you guys have a more detailed protocol of it.

**Comment by ClydeChenT** [comment]
@mikeller I see. I can continue to capture these data from USB. Thank you anyway.
