### ISSUE TITLE
[Request] Downscaling to smaller screen resolution

### ISSUE THREAD

**Issue by derlui** [cleanflight/cleanflight-configurator#448]
I'd like to setup a solar powered Raspberry Pi with 7" screen as a kiosk computer for all fellow pilots to use with Cleanflight / Betaflight / Raceflight / BLHeli during a day out flying. At the moment though, this solution is quite hard to use since the interface does not scale down to smaller screens (like the 720x480 in my case) or allow scrolling. Would it be possible to implement that?

**Comment by hydra** [comment]
not something we're interested in right now but feel free to create a PR if you have time.
