### ISSUE TITLE
How to install later version of cleanflight-configurator

### ISSUE THREAD

**Issue by pechovic** [cleanflight/cleanflight-configurator#458]
Hi, can someone advise me on how to install later version of cleanflight configurator. Unfortunately the current version 2.0.0.0 doesn't support management of the older cleanflight firmwares. My aircraft doesn't fly with the new cleanflight firmware (2.0.0.0) and so I don't have the tool to configure older cleanflight firmware because my cleanflight-configurator was updated to this new version.

**Comment by stanislavdimov** [comment]
Cleanflight - Configurator 2.0 can not work  with CF old ver /ver.1***/ with NAZE32 ver 6 /flash but not work/ Why?

**Comment by pechovic** [comment]
Ok, so that has been answered in the video. posted by @stanislavdimov
