### ISSUE TITLE
CleanFlight logo

### ISSUE THREAD

**Issue by Dvogonen** [cleanflight/cleanflight-configurator#46]
I noticed that the CleanFlight configurator is using the Baseflight icon, although in another color. Reusing the BaseFlight logo with such minor changes is problematic in several ways. The biggest problem is that people may not notice the difference at all and confuse BaseFlight and CleanFlight.

I also noticed that there seems to exist no common logo nor graphical profile for CleanFlight neither on the home page, on github or in the configurator itself. Logos and graphical profiles might seem like trivial details, but are important for the recognition and perseption of a open source "brand". High quality software is always branded by some sort of visual implements.

I played with the letters C and F in CleanFlight and made a few scetches of what could be used as both logos and icons. I am not a graphical artist and know that others are far better at this than I am My attempts may perhaps serve as an inspiration for someone else.

![cleanflight3](https://cloud.githubusercontent.com/assets/6105151/5647060/b2a1d3e2-9682-11e4-9ad8-86d1bf0e989e.png)
![cleanflight2](https://cloud.githubusercontent.com/assets/6105151/5647133/57a0c2a4-9683-11e4-8ba4-3a257bea4571.png)
![cleanflight](https://cloud.githubusercontent.com/assets/6105151/5647064/b78181b4-9682-11e4-81de-8ac506def0e6.png)

**Comment by hydra** [comment]
Thanks for these.

Not sure if you're aware but there is a competition going on right now to design a new logo, the details are here:

https://www.facebook.com/permalink.php?story_fbid=623759171067204&id=582474325195689

We definitely want to stick with Green and need them in SVG format.

Any chance you could update them as per the competition details?

**Comment by Dvogonen** [comment]
Had no idea there was an ongoing competition.
I will paint the logos green and enter them.
