### ISSUE TITLE
Reboot without reboot sequence fail

### ISSUE THREAD

**Issue by MauroMombelli** [cleanflight/cleanflight-configurator#460]
I am working on a seriuslypro evo3 and i uploaded my own firmware. Then i wanted to re upload the letest version of CF, so i jumped the boot pin, connected over UART1 with a FTDI chip (DFU is not seen by the system), selected the upload without reboot sequence, loaded the firmware and the upload failed.

Then i downloaded the firmware and manually fleshed with stm32flash without issue, and the board now works normally.

Maybe the system does not support USART upload?

**Comment by hydra** [comment]
works fine, probably you forgot to set the manual baud rate of 256000 for the F3.

**Comment by MauroMombelli** [comment]
you are right, i was not setting manual baudrate, used only no reboot sequence. Why does not work is i don't set the manual baudrate? isn't this a bit counterintuitive?

**Comment by hydra** [comment]
communication with the FC to put the device into bootloader via the running firmware happens at one baud rate, communication wih the FC to flash it using the CPU built-in bootloer happens at a different rate.

**Comment by MauroMombelli** [comment]
But I'm using "no reset" and biit pin shorted; this eliminate the first
communication that send the R. Also the baudrate used for flashing is
dynamically found by the flash software on the first character received.
