### ISSUE TITLE
Cleanflight FW version 2.0.0

### ISSUE THREAD

**Issue by austinpowers1977** [cleanflight/cleanflight-configurator#461]
Hi i have been forced to update to FW V2.0.0 and since then i can not get the GPS to work. Its a fault with the firmware as i changed to baseflight and im getting a gd solid GPS lock indoors. Cant go back to older firmware as it wont let me. Please can you solve this issue. Using NZ GPS. Thanks austin

**Comment by hydra** [comment]
you are not forced, you can still download and use the old configurator with the old firmware if needed.  naze32 doesn't support gps in v2.x unless you build custom firmware yourself.
