### ISSUE TITLE
FW flashing Issue

### ISSUE THREAD

**Issue by xtomj202** [cleanflight/cleanflight-configurator#463]
Tried to flash my Eachine E010S board because the FW update was pushed from the Cleanflight (unable to configure board just cli with a message need FW flash).
No reboot sequence, flash on connect , full chip erase and manual baud rate have I tried to change but without any success. 
What do I have to do to be able to flash the FW? 

BR

J.

**Comment by hydra** [comment]
you need the reboot sequence to get the  board into bootloader mode unless you manually do this via a switch/jumper first.  please use rcgroups for user support, not the github issue tracker.
