### ISSUE TITLE
Manifest file missing

### ISSUE THREAD

**Issue by LunchBox6969** [cleanflight/cleanflight-configurator#472]
Hi,
When attempting to install  an older version of cleanflight. I get the error code manifest file missing or unreadable. What am I doing wrong. Thanks in advance. Matt in FL.

**Comment by McGiverGim** [comment]
I can see the manifest in version 1.x code:

https://github.com/cleanflight/cleanflight-configurator/blob/master_v1.x/manifest.json

**Comment by LunchBox6969** [comment]
Hi guys I was installing  the wrong file got it figured out. Thank you

**Comment by McGiverGim** [comment]
Perfect! You can close the issue, please, if all is ok?
