### ISSUE TITLE
Menu Items Disapear

### ISSUE THREAD

**Issue by bobthemac** [cleanflight/cleanflight-configurator#476]
When I first load everything looks fine and I can get everywhere when I click on the motors, ports, receiver or mode I lose a large chunk of the options like failsafe, servos, GPS, Sensors. I then have to disconnect and reconnect to get the options back.

**Comment by jagwal** [comment]
There is a small switch now on top of the interface next to the "connect" button named "Enable Expert Mode", try that :-)
