### ISSUE TITLE
feature request: combine AUX to enable a defined "mode"

### ISSUE THREAD

**Issue by matoy** [cleanflight/cleanflight-configurator#480]
Hi,

Currently, it's possible to assign multiple AUX channels to a single MODE.
If I understood well, it means if one channel's value match **OR** the other one's does, the mode is enabled.

Wouldn't it be interesting to allow user to use a **"AND"** operator to combine the value from a channel AND the value from another? this would permit to use for example 2 * 3-positions switches on the controller to create a virtual 9-positions switch.

I'm currently new to Cleanflight ; excuse me if this feature request is a non sense :)

Anyway, thank you everybody for your great work!

**Comment by martinbudden** [comment]
I think iNav already has this.

**Comment by matoy** [comment]
Thanks!
