### ISSUE TITLE
Servos page not storing channels

### ISSUE THREAD

**Issue by pinkywafer** [cleanflight/cleanflight-configurator#482]
With Servo_tilt active, I select aux2 for servo0, and press save,  but it is not saved. A check in the cli still shows -90 in the channel instead of 5 as expected.  The same applies for aux 3 or servo 1. (Haven't tried any others)

**Comment by cj7hawk** [comment]
Just noticed this and logged the same fault... I guess it never got fixed.

David.

**Comment by Mmarsian** [comment]
Same for me, have to use cli to configure. If you save on the GUI then cli configuration is deleted.
Not yet fixed.
