### ISSUE TITLE
Periodically getting BOXNAMES

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight-configurator#484]
Is there any reason for https://github.com/cleanflight/cleanflight-configurator/blob/47114c1cf25ceda9267efbc7593714333d14c2c0/js/serial_backend.js#L482 ?

update_live_status() periodically requests BOXNAMES (which can change only on FC reboot), wasting considerable bandwidth.

**Comment by mikeller** [comment]
Isn't `MSP_BOXNAMES` used to query the *available* modes? If so, all tabs that change settings that can affect availability of modes (i.e. probably all of them) should send this request, the periodical querying was probably done as a stopgap because the tabs didn't send the requests.
