### ISSUE TITLE
Serial Port usage

### ISSUE THREAD

**Issue by arnav-gudibande** [cleanflight/cleanflight-configurator#488]
Currently, I have a simple python script that opens a serial port, runs a couple of functions, and then closes the port.

```
import serial

ser = serial.Serial('/dev/ttyUSB0')
print(ser.name) # example function
ser.close()
```

However, after I run this script, cleanflight configurator is not able to successfully establish a connection on on `/dev/ttyUSB0`. The log shows `Serial port successfully opened with ID: 2` and then timeouts after 10 seconds with `Serial port successfully closed`.

As of now, the only way to actually establish a connection after running that script is to fully reboot the computer. Why is cleanflight configurator unable to reopen this serial port?

**Comment by stronnag** [comment]
Perhaps because you leave the port in an indeterminate state. If you run
````
stty sane < /dev/ttyUSB0
````
does that improve things?. fyi I have no problems running arbitrary home made programs (cli save/restore, bb log downlaoder) against CF compatible FCs and subsequently using the configurator.

**Comment by arnav-gudibande** [comment]
Interesting, `stty sane` fixes the issue

**Comment by arnav-gudibande** [comment]
Thanks that worked!

**Comment by mikeller** [comment]
Little addendum: `stty sane -F /dev/<usb device>` is a preferable form of the same command.
