### ISSUE TITLE
Cleanflight configurator V2.1.0-RC1 has problem

### ISSUE THREAD

**Issue by E120103016** [cleanflight/cleanflight-configurator#498]
Hello there:
   The cleanflight configurator V2.1.0-RC1 has a problem. Cause After updating the firmware v2.1.0-RC1, use the cleanflight configurator V2.1.0-RC1. Can not make the settings. Jump directly to the CLI. Is there a problem.

**Comment by trekki1978** [comment]
I'm having the same issue:
![cleanflight - configurator](https://user-images.githubusercontent.com/24782011/28756972-d8185bc2-7579-11e7-926e-4fc68c60aa92.jpg)

**Comment by E120103016** [comment]
The current configuration device V2.1.0 is the same problem. I do not know how to solve. As trekki1978 said the same problem do not know how to inform the changes.TKS!

**Comment by joemonti** [comment]
I had the same issue and believe this fix resolves it -- #503

**Comment by trekki1978** [comment]
The file features.js in the folder "...\AppData\Local\Junemike\User Data\Default\Extensions\enacoimjcgeinfnnnpajinjgmkahmfgb\2.1.0_0\js" seems to be very different from the file changed in the issue #503.

**Comment by trekki1978** [comment]
I could solve this issue and start the configurator after I deleted the "," at the end of line 75:
"{bit: 18, group: 'other', name: 'OSD'}**,**"

I could use the windows editor to change the file FEATURES.JS in folder:
C:\Users\...\AppData\Local\Junemike\User Data\Default\Extensions\enacoimjcgeinfnnnpajinjgmkahmfgb\2.1.0_0\js

Maybe this helps the one or the other user who wants to use the latest CF configurator.

**Comment by E120103016** [comment]
Has been resolved. Thank you very much.
