### ISSUE TITLE
Send anonymous usage switch off problem

### ISSUE THREAD

**Issue by Sh0tek61** [cleanflight/cleanflight-configurator#501]
Why it's impossible to turn off "Receive desktop notifications..." and "Send anonymous usage data..." (upper right corner settings)? CF configurator v.2.0.3, OS Win8.1 x64, Chrome ver.59.0.3071.115 (64bit)

**Comment by tonipalmgren** [comment]
I have the same issue in the stand-alone version of the configurator (installed from "cleanflight-configurator-installer_2.2.0-RC1_win32").

On the Chrome version, I have the "Receive desktop notification when application updates" turned on, and I cannot turn it off. However, the "Send anonymous usage data..." is turned off, and cannot be turned on. Running - OS: Windows, Chrome: 65.0.3325.181, Configurator: 2.1.0.
