### ISSUE TITLE
Cleanflight configurator V2.1.0 has problem

### ISSUE THREAD

**Issue by E120103016** [cleanflight/cleanflight-configurator#502]
The current configuration device V2.1.0 is the same problem. I do not know how to solve. As trekki1978 said the same problem do not know how to inform the changes.TKS!

**Comment by trekki1978** [comment]
I could solve this issue and start the configurator after I deleted the "," at the end of line 75:
"{bit: 18, group: 'other', name: 'OSD'}**,**"

I could use the windows editor to change the file FEATURES.JS in folder:
C:\Users\...\AppData\Local\Junemike\User Data\Default\Extensions\enacoimjcgeinfnnnpajinjgmkahmfgb\2.1.0_0\js

Maybe this helps the one or the other user who wants to use the latest CF configurator.

**Comment by E120103016** [comment]
Thanks! You provide information

**Comment by E120103016** [comment]
已經解決可以使用非常感謝.

**Comment by E120103016** [comment]
Has been resolved. Thank you very much.

**Comment by 7ocb** [comment]
@trekki1978 thanks, that helped me too.
