### ISSUE TITLE
Shield Mode

### ISSUE THREAD

**Issue by ghost** [cleanflight/cleanflight-configurator#507]
Folks are going crazy over the Connex Falcore due to its ease of entry for newb pilots. 

Could a shield mode be incorporated into Cleanflight?

**Comment by McGiverGim** [comment]
``
Falcore’s world first patented SHIELD mode allows anyone to race from day one. SHIELD mode using sonar and barometer sensors,  will automatically maintain flight altitude, and allow pilots to fly close to the ground without the need to maintain altitude.
``
If they use barometer and sonar, you will have more chance of view it implemented in iNav.

Cleanflight has barometer support, to maintain altitude but if you don't use an external unit it will not be too precise. I don't know if this "patented" mode has something different.
