### ISSUE TITLE
Feature request: Access the menus without a flight controller

### ISSUE THREAD

**Issue by tonipalmgren** [cleanflight/cleanflight-configurator#519]
Demo mode, where you can open up the menus without a flight controller connected would help a lot when helping out others. Taking screenshots of different configurator versions is tedious and not practical.

This was requested in 2015, but the issue was closed. I'm wondering if others would find this useful and could this be done with reasonable effort.

**Comment by hydra** [comment]
yes it would be useful indeed. if you have any thoughts on how you would go about implementing it please comment below.  Are you going to attempt it?
