### ISSUE TITLE
MSP - Shorten MSP response loss recovery time

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight-configurator#52]
When target stops responding to MSP requests (in debugger in my case), it seems that callback handlers are still created in configurator. It takes quite long to recover when connection is restored, during this time the app is frozen.

Old (just before graphics update) version did handle this gracefully

**Comment by hydra** [comment]
Please test 0.63.1.  A bug fix was applied which may have helped.

**Comment by skaman82** [comment]
This issue is soooo old. @ledvinap can we close this?

**Comment by ledvinap** [comment]
Did not hit the problem lately ...
