### ISSUE TITLE
ARMing with 4 channel

### ISSUE THREAD

**Issue by MauroMombelli** [cleanflight/cleanflight-configurator#520]
I have an old transmitter with only 4 channel, and I would like to use it for a little quad, but i can't find any option to ARM without using any AUX channel.. is this possible at all?

**Comment by mikeller** [comment]
Yes, that's simple. It's called 'stick arming', and it's the default when no channel is assigned for arming: https://github.com/cleanflight/cleanflight/blob/master/docs/Controls.md

**Comment by MauroMombelli** [comment]
it works, thanks, i had to delete te ARM channel for AUX1
