### ISSUE TITLE
Cleanflight development project build error

### ISSUE THREAD

**Issue by rohith2606** [cleanflight/cleanflight-configurator#524]
during project build in eclipse, i am getting these errors and not able to find a solution for it. Kindly provide some assistance to overcome these errors and obtain the Hex files. I tried for spracingf3evo, stm32f3discovery and sprcingf3, all showed the same errors.

make: *** [Makefile:418: hex] Error 2	

make[1]: *** [Makefile:294: obj/main/cleanflight_SPRACINGF3.elf] Error 1

obj/main/cleanflight_SPRACINGF3.elf section `.text' will not fit in region 'FLASH'	   

region `FLASH' overflowed by 48075 bytes

**Comment by mikeller** [comment]
@rohith2606: Looks like you are trying to do debug builds. These will not fit into the flash space available on F3 boards unless you remove **a lot** of the features.
