### ISSUE TITLE
No Linux build available of v2.6.0 release in June

### ISSUE THREAD

**Issue by neuhaus** [cleanflight/cleanflight-configurator#545]
This is a duplicate of #543 which was closed by the bot.

There are still no Linux packages available for version 2.6.0.

The last version of the Linux binaries is from 2018.

**Comment by neuhaus** [comment]
Bad bot

**Comment by neuhaus** [comment]
Bad bot

**Comment by neuhaus** [comment]
Bad bot

**Comment by neuhaus** [comment]
@hydra Hi, can you build the binary or does someone else do this?

**Comment by hydra** [comment]
@neuhaus Hey, sorry for late reply to this, I recall trying, and then running into some of the usual linux pain, the result of the build was this:
```
[13:47:21] Error: Command failed: dpkg-deb --build ./release//cleanflight-configurator_2.6.0_amd64
dpkg-deb: warning: parsing file './release//cleanflight-configurator_2.6.0_amd64/DEBIAN/control' near line 7 package 'cleanflight-configurator':
 missing description
dpkg-deb: warning: parsing file './release//cleanflight-configurator_2.6.0_amd64/DEBIAN/control' near line 7 package 'cleanflight-configurator':
 missing maintainer
dpkg-deb: error: control directory has bad permissions 777 (must be >=0755 and <=0775)
```

I'm gonna have another shot at it now and see what I can do.

I'm using WSL + Ubuntu to build.  It basically seems like the debian package generator can't run under WSL and/or there are bugs and/or magic runes which I don't know.

If anyone can help it'd be greatly appreciated.

**Comment by hydra** [comment]
Gonna close this, and re-open the original #543

**Comment by mikeller** [comment]
@hydra: If you are running on a Windows host it is probably the easiest if you use VirtualBox or similar and install a small-ish linux VM to use for building the linux packages.
