### ISSUE TITLE
Cosmetic Bug: In Receiver Tab, AUX channels 9-12 don't show on graph ?

### ISSUE THREAD

**Issue by enly1** [cleanflight/cleanflight-configurator#58]
Not hugely important, but for channels 9-12 , no graph data appears to be displayed when receiver channel gets updated.  The bar graph (Green bars) displays the inputs, but its not logged on the scrolling graph.

**Comment by hydra** [comment]
Should be fixed in c5fb803e29f7052dccf929834283a750a978fca4
