### ISSUE TITLE
Associate PID Controller to PID Profile

### ISSUE THREAD

**Issue by cjbraden** [cleanflight/cleanflight-configurator#61]
Would it be possible to assign a PID controller (since we have a few choices now) to a specific pid bank so that when we switch PID banks we would also switch the controller with it, allowing us to compare controllers in the field?

**Comment by vadav** [comment]
Agree, link pid_controller to the profiles and/or with modes

**Comment by hydra** [comment]
`pid_controller` is already linked to profile.  you can see this in the output from the `dump profile` cli command.

**Comment by hydra** [comment]
Please open a new issue if you would like to be able to configure the pid controller for the configurator though and reference this if you do so.
