### ISSUE TITLE
Flashing - Support STM32F3 based targets in DFU mode.

### ISSUE THREAD

**Issue by MJ666** [cleanflight/cleanflight-configurator#65]
Looks to be the code already contain parts to enable DFU flashing? Not sure what the actual state is and if this part of the code is already working. Actually the GUI is only allowing Hex files to be selected and will do some basic tests. Also an STM device in boot mode is not detected by the GUI. Would be nice to be able to flash all targets easily via the GUI.

I have opened an related issue in CF already:
https://github.com/cleanflight/cleanflight/issues/412

**Comment by MJ666** [comment]
@hydra this may be also get interesting for you with the SP Racing F3?

**Comment by hydra** [comment]
SPRacing F3 uses CP2102, no DFU required.  Sparky requires DFU mode.

**Comment by andymac4182** [comment]
@hydra Is there anything special other that shorting the boot pins to flash the SPRacingF3 if you disabled UART1 by mistake?

**Comment by andymac4182** [comment]
I have been working through this and it seems mostly there. The only issue I have now is the getDevices (https://developer.chrome.com/apps/usb#method-getDevices) function doesn't return a device even through I can see it in DFU mode and flash it with other software. Any ideas or pointers?

**Comment by tracernz** [comment]
Have you added the USB VID/PID to the manifest? It will only return devices you have permissions to access.

**Comment by andymac4182** [comment]
They are added already in the existing Configurator. I confirmed they are correct. Been busy with work but going back to look at this soon.

**Comment by tracernz** [comment]
They are listed as optional permissions though. You will need to make sure you request them somewhere. https://developer.chrome.com/apps/permissions#method-request

**Comment by tracernz** [comment]
I had a look at this. You need to uncomment this line and then click the button on the landing page to request USB permissions: https://github.com/cleanflight/cleanflight-configurator/blob/master/tabs/landing.js#L13.

Then this line needs to go below line 356: https://github.com/cleanflight/cleanflight-configurator/blob/master/js/protocols/stm32usbdfu.js#L300

After that I successfully flashed my STM32F3 Discovery board using USB-DFU. I did note the code isn't really complete in that it doesn't handle some error conditions properly though.

**Comment by andymac4182** [comment]
I will check this out again. I couldn't get it working on my version of Chrome.

**Comment by tracernz** [comment]
I've submitted a PR which makes the minimal changes, please test that. :)

**Comment by skaman82** [comment]
@MJ666 can we close this?

**Comment by MJ666** [comment]
Sorry will close it.
