### ISSUE TITLE
Add option to use simple checkbox AUX configurator

### ISSUE THREAD

**Issue by wobbletop** [cleanflight/cleanflight-configurator#7]
For new users, the checkbox format was sufficient and for most users, sufficient as well.

New range format adds complexity and would slow adoption of cleanflight by users.

**Comment by fiveangle** [comment]
Yes, old way was "old" while the new way is far more flexible and mimics the cause-effect relationship between what they program in their TX, while the checkboxes corresponded to nothing but "that's how baseflight works".

-=dave

**Comment by SlyMike** [comment]
I love the sliders for setting up the AUX channels. I think this is a real benefit. I can get 12 modes from a 6 position switch + 1 toggle, 6 functions from a 3 position switch + 3 toggles and have OSD on/off and cam stab on/off on one channel over 2 toggle switches..... All with a budget Tx.
If anything this tab should be considered the "basic" version with an "advanced" mode that lets the user link other (system / non-radio) variables to functions.

For instance: If the barometer reads over X meters initiate ALT hold, If the battery is less than Y volts, turn off some LEDs, If the sonar reads less than 0.5m move a servo (auto landing gear). The possibilities are endless.

**Comment by hydra** [comment]
Closing this, people seem to be fine with it, no issues rasied since the initial objections.

**Comment by max3228** [comment]
OK, I am fine with you closing #7.
Dominic thanks for all your hard work on Cleanflight.
 
Regards,
Mike
 

  _____
