### ISSUE TITLE
Tabs disappear when connected

### ISSUE THREAD

**Issue by t0mmg** [cleanflight/cleanflight-configurator#70]
On the version 0.60.0, before I connect the tab controls (Setup, Ports, Configuration) are visible, when I click Connect, the tab controls then disappear:
![image](https://cloud.githubusercontent.com/assets/4988292/5892923/6ea3e4fa-a4c9-11e4-94ee-8277d6610146.png)
I can click on them by guessing the position of the tabs.
Display adaptor is Intel HD Graphics 3000

**Comment by hydra** [comment]
This is fixed in latest development branch.
