### ISSUE TITLE
Status - Add FC state indicators

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight-configurator#74]
Adding indicators for system status would be useful.

three important states are: calibrating, armed and failsafe.

**Comment by hydra** [comment]
RX loss potentially available in addition to failsafe state now too.

Blackbox device capacity/state might be nice too - so you remember to download or erase it.

**Comment by gaelj** [comment]
I have attempted to implement these features.
Please check and report any feedback on 
https://github.com/gaelj/cleanflight-configurator

**Comment by gaelj** [comment]
Is RX_loss readily available in MSP or does it require to be implement in CF as well ?

**Comment by skaman82** [comment]
Armed, failsafe, serial link and battery status are finaly added in https://github.com/cleanflight/cleanflight-configurator/pull/372

**Comment by skaman82** [comment]
I think we can close this one
