### ISSUE TITLE
PID Controller Dropdown

### ISSUE THREAD

**Issue by t0mmg** [cleanflight/cleanflight-configurator#83]
In Development version 0.61.0, the alignment of the text in the PID Controller dropdown is too far to the right obscuring the value of the box when the dropdown box isn't open:
![image](https://cloud.githubusercontent.com/assets/4988292/5967855/566b9ce6-a809-11e4-98f5-2ccdd71d9d18.png)

and

![image](https://cloud.githubusercontent.com/assets/4988292/5967869/6999b06e-a809-11e4-8d04-2e5583cea302.png)

Thanks

**Comment by waslater** [comment]
I was just about to ask for a PID Controller menu in the GUI. Glad it's in development! :)

**Comment by hydra** [comment]
This should be fixed already. If not please re-open.
