### ISSUE TITLE
Add range limits to "Board Alignment" adjustment descriptions

### ISSUE THREAD

**Issue by fiveangle** [cleanflight/cleanflight-configurator#84]
Previous to the "Board Alignment" feature implementation in CFC, users would adjust board alignment via cli, with many used to 0-360 notation.

Example:
set align_board_yaw = 270

The "Board Alignment" feature in CFC enforces "-180" to "+180" range limits, causing confustion for new users who attempt to enter "270" when they should use "-90".

Please replace the "[deg]" description in the Board Alignment feature variables with the allowable ranges of -180 deg to +180 deg, or lift the restriction and allow 0-360 notation.

-=dave

**Comment by hydra** [comment]
Done, allowable limits are -180 to +360
