### ISSUE TITLE
Status - Show the current profile

### ISSUE THREAD

**Issue by Sil20** [cleanflight/cleanflight-configurator#87]
The profile selection combobox is in the PID tuning folder though it is related to most features (Receiver, Modes...)

this combobox should be either availabel in all related folder OR in a unique place outside the folders

**Comment by hydra** [comment]
Folder?  Do you mean tab?  Yes I agree it's misplaced.

**Comment by Sil20** [comment]
Sorry I am not a that english fluent.
 Yes I meant Tab.

**Comment by matvey83** [comment]
+1  the Profiles checkbox should be moved outside of PID Tuning tab.   Maybe above the tabs, or to the bottom of the UI, below the tab widget.

**Comment by skaman82** [comment]
this is done in PR https://github.com/cleanflight/cleanflight-configurator/pull/286

**Comment by skaman82** [comment]
Done in configurator 1.2. closing
