### ISSUE TITLE
split pitch and roll pid in flight adjustments

### ISSUE THREAD

**Issue by xxlegacyxx** [cleanflight/cleanflight-configurator#9]
Is there a way to separate the pitch and roll in flight pid adjustments so they can be tuned separately tuning both at the same time will not worl for most setups

**Comment by vadav** [comment]
I support this, most multis need diff pids on pitch and roll..

**Comment by maralcbr** [comment]
Would be very nice to have this feature.

**Comment by hydra** [comment]
Done in 5f05e4c8cc4ce3f4e60b6ba1e8a1c5a0e2ade076
