### ISSUE TITLE
No indication of orientation when custom mixer selected

### ISSUE THREAD

**Issue by nebbian** [cleanflight/cleanflight-configurator#92]
When a custom mix is selected, there is no indication of which direction the quad is facing in the GUI.  This is a backwards step from previous versions, which at least showed a box.

**Comment by hydra** [comment]
Yeah. There is a problem there. I noticed the same thing the other day.  Probably a simple fix with the model loading code. PR?

**Comment by thenickdude** [comment]
Caused by #105
